(function(){
  'use strict';
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const fmt=v=>Number(v).toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2});
  const uniq=a=>[...new Set(a.filter(Boolean))];
  const CACHE_TTL=10*60*1000;
  const chartCache=new Map(),searchCache=new Map();
  let stocks=[],days=180,charts=[];
  const known=[
    ['854075','Berkshire Hathaway Inc. Class A','BRK-A'],['A0YJQ2','Berkshire Hathaway Inc. Class B','BRK-B'],['918422','NVIDIA Corporation','NVDA'],['870747','Microsoft Corporation','MSFT'],['865985','Apple Inc.','AAPL'],['906866','Amazon.com, Inc.','AMZN'],['716460','SAP SE','SAP'],['723610','Siemens AG','SIE.DE'],['840400','Allianz SE','ALV.DE'],['A11099','Arista Networks, Inc.','ANET'],['A1CX3T','Tesla, Inc.','TSLA'],['A2JG9Z','Broadcom Inc.','AVGO'],['850628','JPMorgan Chase & Co.','JPM'],['858560','Eli Lilly and Company','LLY'],['938914','Airbus SE','AIR.PA'],['909800','Taiwan Semiconductor Manufacturing Company Limited','TSM'],['A1J4U4','ASML Holding N.V.','ASML'],['A3CSML','GE Aerospace','GE'],['A0B87V','Salesforce, Inc.','CRM'],['871460','Oracle Corporation','ORCL'],['552484','Netflix, Inc.','NFLX'],
    ['A14Y6F','Alphabet Inc. Class A','GOOGL'],['A1JWVX','Meta Platforms, Inc.','META'],['863186','Advanced Micro Devices, Inc.','AMD'],['A2J7M9','Visa Inc.','V'],['A0F602','Mastercard Incorporated','MA'],['871981','Adobe Inc.','ADBE'],['878841','Cisco Systems, Inc.','CSCO'],['883121','Qualcomm Incorporated','QCOM'],['852654','Texas Instruments Incorporated','TXN'],['888351','Costco Wholesale Corporation','COST'],['856958',"McDonald's Corporation",'MCD'],['850663','Coca-Cola Company','KO'],['852062','Procter & Gamble Company','PG'],['860853','Walmart Inc.','WMT'],['853260','Johnson & Johnson','JNJ'],['A2QA4J','Palantir Technologies Inc.','PLTR'],['A2PHHG','Uber Technologies, Inc.','UBER'],['A2JEXP','Booking Holdings Inc.','BKNG'],['850598','Caterpillar Inc.','CAT'],['870153','Honeywell International Inc.','HON'],['894648','Lockheed Martin Corporation','LMT'],['A2DSYC','Linde plc','LIN'],['857209','Thermo Fisher Scientific Inc.','TMO'],['888024','Intuitive Surgical, Inc.','ISRG'],['851995','PepsiCo, Inc.','PEP'],['851399','IBM','IBM'],['868440','AT&T Inc.','T'],['868402','Verizon Communications Inc.','VZ'],['852549','Exxon Mobil Corporation','XOM'],['852552','Chevron Corporation','CVX'],
    ['853292','LVMH','MC.PA'],['860180','Schneider Electric','SU.PA'],['886670','Hermes International','RMS.PA'],['850727','TotalEnergies SE','TTE.PA'],['920657','Sanofi','SAN.PA'],['863195','EssilorLuxottica','EL.PA'],['850133','Air Liquide','AI.PA'],['887771','BNP Paribas','BNP.PA'],['855705','AXA','CS.PA'],['867475','Vinci','DG.PA'],['555750','Deutsche Telekom AG','DTE.DE'],['843002','Munich Re','MUV2.DE'],['623100','Infineon Technologies AG','IFX.DE'],['710000','Mercedes-Benz Group AG','MBG.DE'],['519000','BMW AG','BMW.DE'],['766403','Volkswagen AG','VOW3.DE'],['515100','BASF SE','BAS.DE'],['555200','DHL Group','DHL.DE'],['703000','Rheinmetall AG','RHM.DE'],['514000','Deutsche Bank AG','DBK.DE'],['CBK100','Commerzbank AG','CBK.DE'],['A2JNF4','Adyen N.V.','ADYEN.AS'],['A2PRDK','Prosus N.V.','PRX.AS'],['A3EU6F','Novo Nordisk A/S','NOVO-B.CO'],['A1C0ZC','DSV A/S','DSV.CO'],['855167','Roche Holding AG','ROG.SW'],['904278','Novartis AG','NOVN.SW'],['A12DFH','UBS Group AG','UBSG.SW'],['579919','Zurich Insurance Group','ZURN.SW'],['919730','ABB Ltd','ABBN.SW'],['852147','Rio Tinto plc','RIO.L'],['886455','AstraZeneca PLC','AZN.L'],['A3C99G','Shell plc','SHEL.L'],['A0JNE2','Unilever PLC','ULVR.L'],['923893','HSBC Holdings plc','HSBA.L'],['850517','BP p.l.c.','BP.L'],['A3EQR4','RELX plc','REL.L'],['A0JEJF','London Stock Exchange Group','LSEG.L'],['A2ACKK','Ferrari N.V.','RACE.MI'],
    ['A117ME','Alibaba Group Holding Limited','BABA'],['A1138D','Tencent Holdings Limited','0700.HK'],['853510','Toyota Motor Corporation','7203.T'],['853687','Sony Group Corporation','6758.T'],['878610','Keyence Corporation','6861.T'],['865510','Tokyo Electron Limited','8035.T'],['657892','Mitsubishi UFJ Financial Group','8306.T'],['853219','Hitachi, Ltd.','6501.T'],['A12B2R','Recruit Holdings Co., Ltd.','6098.T'],['864009','Nintendo Co., Ltd.','7974.T'],['891624','SoftBank Group Corp.','9984.T'],['859579','Shin-Etsu Chemical Co., Ltd.','4063.T'],['888322','Samsung Electronics Co., Ltd.','005930.KS'],['A0MZ1Y','SK Hynix Inc.','000660.KS'],['885166','Hyundai Motor Company','005380.KS'],['A2JR2L','PDD Holdings Inc.','PDD'],['A112ST','JD.com, Inc.','JD'],['A0F5DE','Baidu, Inc.','BIDU'],['A2N5NR','Meituan','3690.HK'],['A0MN2Z','ICICI Bank Limited','IBN'],['A0X9JL','HDFC Bank Limited','HDB'],['946271','Reliance Industries Limited','RELIANCE.NS'],['850524','BHP Group Limited','BHP.AX'],['882695','Commonwealth Bank of Australia','CBA.AX'],['890068','CSL Limited','CSL.AX'],['A0F5K1','Macquarie Group Limited','MQG.AX'],['A3C6AE','Woodside Energy Group Ltd','WDS.AX'],
    ['A14TJP','Shopify Inc.','SHOP'],['852173','Royal Bank of Canada','RY'],['852684','Toronto-Dominion Bank','TD.TO'],['865114','Canadian Natural Resources','CNQ'],['885427','Enbridge Inc.','ENB'],['A0MYNP','MercadoLibre, Inc.','MELI'],['897998','Vale S.A.','VALE'],['899026','Petroleo Brasileiro S.A.','PBR'],['886561','Atlas Copco AB','ATCO-A.ST'],['855689','Volvo AB','VOLV-B.ST'],['865956','Sandvik AB','SAND.ST'],['A2P4AH','EQT AB','EQT.ST'],['881050','KONE Oyj','KNEBV.HE'],['870737','Nokia Oyj','NOKIA.HE'],['881360','Wärtsilä Oyj','WRT1V.HE']
  ];
  const local=known.map(x=>({wkn:x[0],name:x[1],symbol:x[2]})),localMap=new Map(local.map(x=>[x.wkn.toUpperCase(),x]));
  function setProgress(p,status,step){$('progressWrap').style.display='block';$('progressFill').style.width=p+'%';$('progressPct').textContent=Math.round(p)+' %';$('progressStatus').textContent=status;document.querySelectorAll('.progress-dots span').forEach(x=>x.classList.toggle('active',Number(x.dataset.step)<=step))}
  function cacheGet(key){const x=chartCache.get(key);if(x&&Date.now()-x.ts<CACHE_TTL)return x.data;chartCache.delete(key);return null}
  function cachePut(key,data){chartCache.set(key,{ts:Date.now(),data});if(chartCache.size>8)chartCache.delete(chartCache.keys().next().value)}
  async function fetchJson(url,options={},timeout=3500){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{...options,signal:c.signal,cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return await r.json()}finally{clearTimeout(t)}}
  function yahooUrl(symbol){const end=Math.floor(Date.now()/1000),start=end-60*60*24*1900;return 'https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(symbol)+'?period1='+start+'&period2='+end+'&interval=1d&events=history&includeAdjustedClose=true'}
  function parseChart(z){if(!z)throw Error('keine Kursdaten');const q=z.indicators?.quote?.[0]||{},adj=z.indicators?.adjclose?.[0]?.adjclose||[],vol=q.volume||[];const data=(z.timestamp||[]).map((t,i)=>({d:new Date(t*1000),c:Number.isFinite(adj[i])?adj[i]:q.close?.[i],v:Number.isFinite(vol[i])?vol[i]:0})).filter(x=>Number.isFinite(x.c));if(data.length<252)throw Error('zu wenig Historie');return{data,meta:z.meta||{}}}
  async function yahooChart(symbol){const key=String(symbol).toUpperCase(),cached=cacheGet(key);if(cached)return cached;const url=yahooUrl(symbol);const proxies=['https://corsproxy.io/?url=','https://api.allorigins.win/raw?url='];for(const prefix of proxies){try{const r=await fetchJson(prefix+encodeURIComponent(url),{},2500);const out=parseChart(r.chart?.result?.[0]);cachePut(key,out);return out}catch(_){}}throw Error('Kursdaten für '+key+' konnten nicht geladen werden.');}
  async function yahooSearch(q){const key=q.trim().toLowerCase();if(searchCache.has(key))return searchCache.get(key);const url='https://query1.finance.yahoo.com/v1/finance/search?q='+encodeURIComponent(q)+'&quotesCount=20&newsCount=0';let rows=[];for(const prefix of ['https://corsproxy.io/?url=','https://api.allorigins.win/raw?url=']){try{const direct=await fetchJson(prefix+encodeURIComponent(url),{},2200);rows=(direct.quotes||[]).filter(x=>x.quoteType==='EQUITY'&&x.symbol);if(rows.length)break}catch(_){}}searchCache.set(key,rows);return rows}
  const suffixes={US:[''],NYSE:[''],NASDAQ:[''],XETRA:['.DE'],FRANKFURT:['.F','.DE'],LONDON:['.L'],PARIS:['.PA'],AMSTERDAM:['.AS'],MILAN:['.MI'],MADRID:['.MC'],ZURICH:['.SW'],VIENNA:['.VI'],TOKYO:['.T'],HONGKONG:['.HK'],TORONTO:['.TO'],AUSTRALIA:['.AX'],STOCKHOLM:['.ST'],OSLO:['.OL'],COPENHAGEN:['.CO']};
  function symbolVariants(ticker,ex){const t=String(ticker||'').trim();if(!t)return[];const clean=t.replace('/','-'),dot=t.replace('/','.');const ss=suffixes[String(ex||'').toUpperCase()]||[];return uniq([t,clean,dot,...ss.map(s=>t+s),...ss.map(s=>clean+s),...ss.map(s=>dot+s)])}
  async function openFigi(wkn){const c=new AbortController(),timer=setTimeout(()=>c.abort(),2200);try{const r=await fetch('https://api.openfigi.com/v3/mapping',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify([{idType:'ID_WERTPAPIER',idValue:wkn}]),signal:c.signal});if(r.ok)return await r.json()}catch(_){ }finally{clearTimeout(timer)}return null}
  async function trySymbols(symbols,name){for(const symbol of uniq(symbols).slice(0,6)){try{const p=await yahooChart(symbol);return{name:name||p.meta?.longName||p.meta?.shortName||symbol,symbol,data:p.data,meta:p.meta||{}}}catch(_){}}return null}
  async function resolve(value){const input=value.trim(),upper=input.toUpperCase(),knownHit=localMap.get(upper);if(knownHit){const p=await yahooChart(knownHit.symbol);return{...knownHit,data:p.data,meta:p.meta}}if(/^[A-Z0-9]{6}$/.test(upper)){const figi=await openFigi(upper),rows=figi?.[0]?.data||[],equities=rows.filter(x=>/equity|common stock|depositary receipt|adr|reit/i.test((x.marketSector||'')+' '+(x.securityType||'')+' '+(x.securityType2||'')));for(const e of equities){const hit=await trySymbols(symbolVariants(e.ticker,e.exchCode),e.name||e.securityDescription||e.ticker);if(hit)return{...hit,wkn:upper}}const qs=await yahooSearch(upper);const hit=await trySymbols(qs.map(x=>x.symbol),qs[0]?.longname||qs[0]?.shortname||upper);if(hit)return{...hit,wkn:upper}}const qs=await yahooSearch(input),direct=await trySymbols(qs.map(x=>x.symbol),qs[0]?.longname||qs[0]?.shortname||input);if(direct){const q=qs.find(x=>x.symbol===direct.symbol);return{...direct,wkn:known.find(x=>x[2]===direct.symbol)?.[0]||'',name:q?.longname||q?.shortname||direct.name}}throw Error('„'+input+'“ konnte keinem handelbaren Aktiensymbol zugeordnet werden.')}
  function localMatches(q){const l=q.toLowerCase();return local.filter(x=>x.name.toLowerCase().includes(l)||x.symbol.toLowerCase().startsWith(l)||x.wkn.toLowerCase().startsWith(l)).slice(0,8)}
  function setupAutocomplete(input){const wrap=input.parentElement;wrap.style.position='relative';const box=document.createElement('div');box.className='suggestions';wrap.appendChild(box);let seq=0;const render=rows=>{box._rows=rows;box.innerHTML=rows.map((r,i)=>`<button type="button" data-i="${i}"><b>${esc(r.name)}</b><span>${esc(r.symbol)} · ${r.wkn?'WKN '+esc(r.wkn):'Ticker'}</span></button>`).join('');box.style.display=rows.length?'block':'none'};input.addEventListener('input',async()=>{const q=input.value.trim();if(!q){box.style.display='none';return}const n=++seq;render(localMatches(q));if(q.length<2)return;const rows=await yahooSearch(q);if(n!==seq)return;const merged=[...localMatches(q),...rows.map(x=>({name:x.longname||x.shortname||x.symbol,symbol:x.symbol,wkn:''}))],seen=new Set();render(merged.filter(r=>{const k=r.symbol||r.name;if(seen.has(k))return false;seen.add(k);return true}).slice(0,12))});box.addEventListener('pointerdown',e=>{const b=e.target.closest('button');if(!b)return;e.preventDefault();const r=box._rows?.[Number(b.dataset.i)];if(!r)return;input.value=r.wkn||r.symbol;input.dataset.selected=r.symbol;input.dataset.wkn=r.wkn||'';box.style.display='none'});input.addEventListener('blur',()=>setTimeout(()=>box.style.display='none',180))}
  function destroyCharts(){charts.forEach(c=>{try{c.destroy()}catch(_){}});charts=[]}
  function renderStock(s,i){const z=AKTScoreModel.analyse(s.data),rec=AKTScoreModel.rec(z.score),cls=rec==='KAUFEN'?'buy':rec==='NICHT KAUFEN'?'no':'watch',last=z.last,prev=z.close.at(-2),chg=(last/prev-1)*100;return `<details class="stock-group" ${i===0?'open':''}><summary><div class="summary-main"><b>${esc(s.name)}</b><span>${esc(s.symbol)}</span></div><strong class="summary-result ${cls}">${rec} · ${z.score}/100</strong></summary><div class="stock-body"><div class="grid"><div class="card"><span class="label">Unternehmen</span><div class="value">${esc(s.name)}</div><div class="sub">${esc(s.symbol)}${s.wkn?' · WKN '+esc(s.wkn):''}</div></div><div class="card"><span class="label">Kurs</span><div class="value">${fmt(last)}</div><div class="sub">${chg>=0?'+':''}${chg.toFixed(2)} %</div></div><div class="card"><span class="label">RSI 14</span><div class="value">${z.rsi.toFixed(1)}</div><div class="sub">${z.rsi<30?'Überverkauft':z.rsi>70?'Überkauft':'konstruktiv'}</div></div><div class="card"><span class="label">Trend</span><div class="value">${last>z.sma200?'AUFWÄRTS':'ABWÄRTS'}</div><div class="sub">SMA 20/50: ${last>z.sma20?'positiv':'negativ'} / ${last>z.sma50?'positiv':'negativ'}</div></div><div class="card wide"><span class="label">Technische Empfehlung</span><div class="score">${rec}</div><div class="sub">Modellscore ${z.score}/100 · Datenqualität ${z.quality}</div><div class="meter"><span style="width:${z.score}%"></span></div></div><div class="card"><span class="label">Momentum 3M</span><div class="value">${z.momentum3.toFixed(1)} %</div></div><div class="card"><span class="label">Momentum 12M</span><div class="value">${z.momentum12.toFixed(1)} %</div></div><div class="card"><span class="label">Volatilität</span><div class="value">${z.volatility.toFixed(1)} % p.a.</div><div class="sub">${z.volatility<20?'niedrig':z.volatility<30?'mittel':z.volatility<45?'erhöht':'hoch'}</div></div><div class="card"><span class="label">Volumen-Bestätigung</span><div class="value">${z.volumeRatio.toFixed(2)}×</div><div class="sub">20T / 60T</div></div><div class="card wide"><span class="label">SMA 20 / 50 / 200</span><div class="value">${[z.sma20,z.sma50,z.sma200].map(fmt).join(' / ')}</div></div><div class="card"><span class="label">Unterstützung</span><div class="value">${fmt(Math.min(...z.close.slice(-60)))}</div></div><div class="card"><span class="label">Widerstand</span><div class="value">${fmt(Math.max(...z.close.slice(-60)))}</div></div></div><div class="stock-charts"><div class="chart"><div class="chart-title">Kurs + SMA 20 / 50 / 200</div><canvas id="price-${i}"></canvas></div><div class="chart small"><div class="chart-title">RSI 14</div><canvas id="rsi-${i}"></canvas></div><div class="chart small"><div class="chart-title">MACD</div><canvas id="macd-${i}"></canvas></div></div><section class="card why"><b>Warum diese Bewertung?</b><ul>${z.reasons.map(x=>'<li>'+esc(x)+'</li>').join('')}</ul></section></div></details>`}
  function drawCharts(s,i){const v=s.data.slice(-Math.max(30,days)),a=v.map(x=>x.c),labels=v.map(x=>x.d.toLocaleDateString('de-DE')),smaLine=n=>v.map((_,j)=>j<n-1?null:AKTScoreModel.sma(a.slice(0,j+1),n));charts.push(new Chart($('price-'+i),{type:'line',data:{labels,datasets:[{label:'Kurs',data:a,pointRadius:0,borderWidth:2},{label:'SMA 20',data:smaLine(20),pointRadius:0},{label:'SMA 50',data:smaLine(50),pointRadius:0},{label:'SMA 200',data:smaLine(200),pointRadius:0}]},options:{responsive:true,maintainAspectRatio:false,animation:false,interaction:{mode:'index',intersect:false}}}));const rs=v.map((_,j)=>j<14?null:AKTScoreModel.rsi(a.slice(0,j+1)));charts.push(new Chart($('rsi-'+i),{type:'line',data:{labels,datasets:[{label:'RSI 14',data:rs,pointRadius:0,borderWidth:2},{label:'70',data:labels.map(()=>70),pointRadius:0},{label:'30',data:labels.map(()=>30),pointRadius:0}]},options:{responsive:true,maintainAspectRatio:false,animation:false,scales:{y:{min:0,max:100}}}}));const m=AKTScoreModel.macd(a);charts.push(new Chart($('macd-'+i),{type:'line',data:{labels,datasets:[{label:'MACD',data:m.values,pointRadius:0,borderWidth:2},{label:'Signal',data:m.signalValues,pointRadius:0}]},options:{responsive:true,maintainAspectRatio:false,animation:false}}))}
  function render(){destroyCharts();$('individuals').innerHTML=stocks.map(renderStock).join('');requestAnimationFrame(()=>stocks.forEach((s,i)=>drawCharts(s,i)))}
  function finish(){setProgress(100,'Analyse abgeschlossen.',6);setTimeout(()=>$('progressWrap').style.display='none',800)}
  async function submit(e){e.preventDefault();$('err').style.display='none';$('analyzeBtn').disabled=true;$('app').style.display='none';$('top10Panel').open=false;setProgress(5,'Eingaben werden geprüft …',1);try{const vals=uniq(['wkn1','wkn2','wkn3'].map(id=>$(id).value.trim()).filter(Boolean));if(!vals.length)throw Error('Bitte mindestens einen Titel eingeben.');if(vals.length>3)throw Error('Maximal drei Titel gleichzeitig.');const results=[];setProgress(15,'Wertpapiere werden aufgelöst …',2);for(let i=0;i<vals.length;i++){setProgress(18,'Wertpapier '+(i+1)+'/'+vals.length+' wird aufgelöst …',2);results.push(await resolve(vals[i]));setProgress(30+(i+1)*15,'Kursdaten geladen · '+(i+1)+'/'+vals.length,4)}stocks=results;setProgress(82,'Datenbasis und Signale werden geprüft …',5);$('app').style.display='block';render();finish()}catch(err){$('err').textContent=err.message||'Analyse konnte nicht geladen werden.';$('err').style.display='block';setProgress(100,'Analyse fehlgeschlagen.',6)}finally{$('analyzeBtn').disabled=false}}
  function top10Card(x,i){return `<div class="top10-item"><div><div class="top10-rank">#${i+1}</div><div class="top10-name">${esc(x.name)}</div><div class="top10-symbol">${esc(x.symbol)}</div><div class="top10-wkn">WKN ${esc(x.wkn||'—')}</div></div><div><div class="top10-score">${Math.round(x.score)}/100</div><div class="top10-meta"><span>${x.price?fmt(x.price):''}</span><span>${x.change==null?'':Number(x.change).toFixed(2)+'%'}</span></div><button class="top10-detail" type="button" data-wkn="${esc(x.wkn||x.symbol)}">＋ Detailanalyse</button></div></div>`}
  async function loadTop10(){const grid=$('top10Grid');grid.innerHTML='<div class="top10-loading">Schnell-Cache wird geladen …</div>';try{const r=await fetch('./top10.json?ts='+Date.now(),{cache:'no-store'}),j=await r.json();const items=(j.items||[]).map(x=>({...x,score:Math.round(Number(x.score))})).filter(x=>Number.isFinite(x.score)&&x.score>=90).sort((a,b)=>b.score-a.score).slice(0,10);grid.innerHTML=items.length?items.map(top10Card).join(''):'<div class="top10-empty">Aktuell kein Titel mit mindestens 90/100.</div>';$('top10Date').textContent=j.generatedAt?'Stand '+new Date(j.generatedAt).toLocaleString('de-DE',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'Aktuell'}catch(_){grid.innerHTML='<div class="top10-empty">Top-10-Daten vorübergehend nicht verfügbar.</div>'}}
  function init(){['wkn1','wkn2','wkn3'].forEach(id=>setupAutocomplete($(id)));$('form').addEventListener('submit',submit);document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');days=Number(b.dataset.d);if(stocks.length)render()}));$('openAll').onclick=()=>document.querySelectorAll('.stock-group').forEach(x=>x.open=true);$('closeAll').onclick=()=>document.querySelectorAll('.stock-group').forEach(x=>x.open=false);$('top10Grid').addEventListener('click',e=>{const b=e.target.closest('.top10-detail');if(!b)return;const input=$('wkn1');input.value=b.dataset.wkn;$('form').requestSubmit()});loadTop10()}
  document.addEventListener('DOMContentLoaded',init,{once:true});
})();
