(function(){'use strict';
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const cache=new Map(), selected=new Map();
const local=[['ama','Amazon.com, Inc.','AMZN','906866'],['amazon','Amazon.com, Inc.','AMZN','906866'],['tes','Tesla, Inc.','TSLA','A1CX3T'],['tesla','Tesla, Inc.','TSLA','A1CX3T'],['mic','Microsoft Corporation','MSFT','870747'],['microsoft','Microsoft Corporation','MSFT','870747'],['app','Apple Inc.','AAPL','865985'],['apple','Apple Inc.','AAPL','865985'],['nvi','NVIDIA Corporation','NVDA','918422'],['nvidia','NVIDIA Corporation','NVDA','918422'],['ane','Arista Networks, Inc.','ANET','A11099'],['arista','Arista Networks, Inc.','ANET','A11099'],['alv','Allianz SE','ALV','840400'],['allianz','Allianz SE','ALV','840400'],['sap','SAP SE','SAP','716460'],['siemens','Siemens AG','SIE','723610']];
function localMatches(q){q=q.toLowerCase();return local.filter(x=>x[0].startsWith(q)||x[1].toLowerCase().includes(q)||x[2].toLowerCase().startsWith(q)||x[3].toLowerCase().startsWith(q));}
async function remoteMatches(q){if(cache.has(q))return cache.get(q);const out=[];const u='https://query1.finance.yahoo.com/v1/finance/search?q='+encodeURIComponent(q)+'&quotesCount=20&newsCount=0';for(const make of [x=>'https://corsproxy.io/?url='+encodeURIComponent(x),x=>'https://api.allorigins.win/raw?url='+encodeURIComponent(x)]){try{const r=await fetch(make(u));if(!r.ok)continue;const j=await r.json(),seen=new Set();for(const x of j.quotes||[]){if(x.quoteType!=='EQUITY'||!x.symbol)continue;const s=String(x.symbol).toUpperCase();if(seen.has(s))continue;seen.add(s);out.push(['',x.longname||x.shortname||s,s,'']);if(out.length>=12)break}if(out.length)break}catch(_){}}cache.set(q,out);return out}
function style(){if($('#dynamicAutocompleteStyle'))return;const s=document.createElement('style');s.id='dynamicAutocompleteStyle';s.textContent='.dynamic-stock-suggestions{position:absolute;z-index:100000;left:0;right:0;top:calc(100% + 4px);display:none;background:#fff;color:#172033;border:1px solid #cbd5e1;border-radius:10px;box-shadow:0 12px 30px rgba(15,23,42,.2);max-height:320px;overflow:auto}.dynamic-stock-suggestion{display:flex;width:100%;flex-direction:column;align-items:flex-start;padding:10px 12px;border:0;border-bottom:1px solid #eef2f7;background:#fff;color:#172033;text-align:left;cursor:pointer}.dynamic-stock-suggestion:hover{background:#f1f5f9}.dynamic-stock-suggestion b{font-size:14px}.dynamic-stock-suggestion span{font-size:11px;color:#64748b}';document.head.appendChild(s)}
function setup(input){if(!input||input.dataset.dynamicAutocomplete)return;input.dataset.dynamicAutocomplete='1';const p=input.parentElement;if(!p)return;p.style.position='relative';style();const box=document.createElement('div');box.className='dynamic-stock-suggestions';p.appendChild(box);let seq=0;const render=rows=>{box._rows=rows;box.innerHTML=rows.map((r,i)=>'<button type="button" class="dynamic-stock-suggestion" data-i="'+i+'"><b>'+esc(r[1])+'</b><span>'+esc(r[2])+(r[3]?' · WKN '+esc(r[3]):' · Ticker wird direkt aufgelöst')+'</span></button>').join('');box.style.display=rows.length?'block':'none'};input.addEventListener('input',async()=>{const q=input.value.trim();input.dataset.selectedSymbol='';input.dataset.selectedWkn='';if(!q){box.style.display='none';return}const n=++seq;render(localMatches(q));if(q.length<2)return;const remote=await remoteMatches(q);if(n!==seq)return;const all=[...localMatches(q),...remote],seen=new Set(),merged=[];for(const r of all){const k=(r[2]||r[3]||r[1]).toUpperCase();if(seen.has(k))continue;seen.add(k);merged.push(r);if(merged.length>=12)break}render(merged)});box.addEventListener('pointerdown',e=>{const b=e.target.closest('button');if(!b)return;e.preventDefault();const r=box._rows?.[+b.dataset.i];if(!r)return;const symbol=(r[2]||'').toUpperCase(),wkn=(r[3]||'').toUpperCase();input.value=wkn||symbol;input.dataset.selectedSymbol=symbol;input.dataset.selectedWkn=wkn;input.dataset.selectedName=r[1]||'';selected.set(input.value.toUpperCase(),{symbol,wkn,name:r[1]||''});box.style.display='none';input.dispatchEvent(new Event('change',{bubbles:true}))});input.addEventListener('blur',()=>setTimeout(()=>box.style.display='none',180))}
function init(){['wkn1','wkn2','wkn3'].forEach(id=>setup($(id)));const original=window.resolve;if(typeof original==='function'&&!window.__aktAutocompleteResolvePatched){window.__aktAutocompleteResolvePatched=true;window.resolve=async function(value,onProgress){const el=[$('wkn1'),$('wkn2'),$('wkn3')].find(x=>x&&x.value.trim().toUpperCase()===String(value).trim().toUpperCase()&&x.dataset.selectedSymbol);const hit=el?{symbol:el.dataset.selectedSymbol,wkn:el.dataset.selectedWkn,name:el.dataset.selectedName}:selected.get(String(value).trim().toUpperCase());if(hit?.symbol){onProgress?.(20,'Ausgewählter Titel wird übernommen …',2);try{const p=await window.chartData(hit.symbol,()=>onProgress?.(65,'Kursdaten werden geladen …',4));return{name:hit.name||p.meta?.longName||p.meta?.shortName||hit.symbol,symbol:hit.symbol,data:p.data,meta:p.meta||{}}}catch(_){}}return original(value,onProgress)}}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();

/* EINZIGES Score-Modell: 100 Punkte, identisch für Detailanalyse und Top-10. */
function mean(a){return a.length?a.reduce((s,v)=>s+v,0)/a.length:null}
function sma(a,n){return a.length>=n?mean(a.slice(-n)):null}
function rsiW(c,n=14){if(c.length<n+1)return 50;let g=0,l=0;for(let i=1;i<=n;i++){const d=c[i]-c[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}g/=n;l/=n;for(let i=n+1;i<c.length;i++){const d=c[i]-c[i-1];g=(g*(n-1)+Math.max(d,0))/n;l=(l*(n-1)+Math.max(-d,0))/n}return l===0?100:100-100/(1+g/l)}
function ema(a,n){if(a.length<n)return[];const k=2/(n+1);let e=mean(a.slice(0,n)),o=[e];for(let i=n;i<a.length;i++){e=a[i]*k+e*(1-k);o.push(e)}return o}
function macd(c){if(c.length<35)return[0,0];const e12=ema(c,12),e26=ema(c,26),m=[];for(let i=0;i<e26.length;i++)m.push(e12[i+14]-e26[i]);const sig=ema(m,9);return[m.at(-1),sig.at(-1)]}
function volatility(c){if(c.length<21)return 0;const r=[];for(let i=c.length-20;i<c.length;i++)r.push(c[i]/c[i-1]-1);const m=mean(r);return Math.sqrt(mean(r.map(x=>(x-m)**2)))*Math.sqrt(252)*100}
function calculateScore(c){if(!Array.isArray(c)||c.length<200)return null;const last=c.at(-1),a20=sma(c,20),a50=sma(c,50),a200=sma(c,200),r=rsiW(c),[m,s]=macd(c),v=volatility(c);let score=0,reasons=[];if(last>a20){score+=10;reasons.push('Kurs über SMA 20.')}else reasons.push('Kurs unter SMA 20.');if(last>a50){score+=10;reasons.push('Kurs über SMA 50.')}else reasons.push('Kurs unter SMA 50.');if(last>a200){score+=20;reasons.push('Kurs über SMA 200 – langfristiger Trend positiv.')}else reasons.push('Kurs unter SMA 200 – langfristiger Trend negativ.');if(r>=50&&r<=65){score+=20;reasons.push('RSI 14 konstruktiv (50–65).')}else if(r>=40&&r<50){score+=15;reasons.push('RSI 14 leicht schwächer.')}else if(r>65&&r<=70){score+=15;reasons.push('RSI 14 erhöht, noch nicht überkauft.')}else if(r>=30&&r<40){score+=10;reasons.push('RSI 14 schwach.')}else if(r<30){score+=6;reasons.push('RSI 14 überverkauft – Risiko erhöht.')}else{score+=6;reasons.push('RSI 14 über 70 – überkauft.')}if(m>s){score+=20;reasons.push('MACD über Signallinie – Momentum positiv.')}else{score+=5;reasons.push('MACD unter Signallinie – Momentum schwach.')}if(v<20){score+=15;reasons.push('Volatilität niedrig.')}else if(v<35){score+=10;reasons.push('Volatilität moderat.')}else if(v<50){score+=6;reasons.push('Volatilität erhöht.')}else{score+=2;reasons.push('Volatilität hoch – erhöhtes Risiko.')}return{score:Math.max(0,Math.min(100,Math.round(score))),r,a20,a50,a200,v,reasons}}
window.calculateScore=calculateScore;
function applyDetailScore(){document.querySelectorAll('.stock-group').forEach(group=>{const canvas=group.querySelector('canvas[id^="price-"]'),chart=canvas&&window.Chart?.getChart(canvas),data=chart?.data?.datasets?.[0]?.data?.map(Number).filter(Number.isFinite)||[],z=calculateScore(data);if(!z)return;const rec=z.score>=70?'KAUFEN':z.score<=44?'NICHT KAUFEN':'BEOBACHTEN',cls=rec==='KAUFEN'?'buy':rec==='NICHT KAUFEN'?'no':'watch';const summary=group.querySelector('.summary-result');if(summary){summary.textContent=rec+' · '+z.score+'/100';summary.className='summary-result '+cls}const tech=[...group.querySelectorAll('.card')].find(x=>x.querySelector('.label')?.textContent.trim()==='Technik-Score');if(tech){const v=tech.querySelector('.value');if(v)v.textContent=z.score+'/100'}const meter=group.querySelector('.meter span');if(meter)meter.style.width=z.score+'%';const why=group.querySelector('.why ul');if(why)why.innerHTML=z.reasons.map(x=>'<li>'+esc(x)+'</li>').join('')})}
function top10Render(items,date){const grid=$('top10Grid');if(!grid)return;grid.innerHTML=items.length?items.slice(0,10).map((x,i)=>'<div class="top10-item"><div><div class="top10-rank">#'+(i+1)+'</div><div class="top10-name">'+esc(x.name)+'</div><div class="top10-symbol">'+esc(x.symbol)+'</div><div class="top10-wkn">WKN '+esc(x.wkn||'—')+'</div><div class="top10-score">'+x.score+'/100</div><div class="top10-meta"><span>'+fmt(x.price)+'</span><span>'+Number(x.change||0).toFixed(2)+'%</span></div></div><button type="button" class="top10-buy" data-top-symbol="'+esc(x.symbol)+'">＋ Detailanalyse</button></div>').join(''):'<div class="top10-empty">Aktuell erreicht kein Titel mindestens 90/100.</div>';if($('top10Date'))$('top10Date').textContent=date||'Live berechnet';grid.querySelectorAll('[data-top-symbol]').forEach(b=>b.onclick=()=>{const el=[$('wkn1'),$('wkn2'),$('wkn3')].find(x=>!x.value);if(el){el.value=b.dataset.topSymbol;el.dataset.selectedSymbol=b.dataset.topSymbol;el.dispatchEvent(new Event('change',{bubbles:true}));$('form')?.requestSubmit()}})}
async function refreshTop10(){const now=Date.now(),key='akt-top10-live-v1',cached=sessionStorage.getItem(key);if(cached){try{const x=JSON.parse(cached);if(now-x.ts<15*60*1000){top10Render(x.items,new Date(x.ts).toLocaleString('de-DE'));return}}catch(_){}}try{const r=await fetch('top10.json',{cache:'no-store'}),j=await r.json(),src=j.items||[],out=[];for(let i=0;i<src.length;i+=3){const batch=src.slice(i,i+3);const res=await Promise.all(batch.map(async x=>{try{const p=await window.chartData(x.symbol),c=p.data.map(y=>Number(y.c)).filter(Number.isFinite),z=calculateScore(c);return z?{...x,score:z.score,price:c.at(-1),change:p.meta?.regularMarketChangePercent??x.change,rsi:Number(z.r.toFixed(1))}:null}catch(_){return null}}));out.push(...res.filter(x=>x&&x.score>=90))}out.sort((a,b)=>b.score-a.score);const items=out.slice(0,10);sessionStorage.setItem(key,JSON.stringify({ts:now,items}));top10Render(items,new Date(now).toLocaleString('de-DE'))}catch(_){top10Render([],'Top-10 nicht verfügbar')}}
let scoreTimer=null;function schedule(){clearTimeout(scoreTimer);scoreTimer=setTimeout(applyDetailScore,250)}
if(document.body)new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});window.addEventListener('load',()=>{setTimeout(applyDetailScore,900);setTimeout(refreshTop10,1100)});setTimeout(refreshTop10,1800);
})();
