(function(){
  'use strict';
  const suffix={XETRA:'.DE',FRANKFURT:'.F',VIENNA:'.VI',NYSE:'',NASDAQ:'',LONDON:'.L',PARIS:'.PA',AMSTERDAM:'.AS',MILAN:'.MI',ZURICH:'.SW',TOKYO:'.T',HONGKONG:'.HK',TORONTO:'.TO'};
  const known={'854075':'BRK-A','A0YJQ2':'BRK-B','918422':'NVDA','870747':'MSFT','865985':'AAPL','906866':'AMZN','716460':'SAP','723610':'SIE.DE','840400':'ALV.DE','A11099':'ANET','A1CX3T':'TSLA','A2JG9Z':'AVGO','850628':'JPM','858560':'LLY','938914':'AIR.PA','909800':'TSM','A1J4U4':'ASML','A3CSML':'GE','A0B87V':'CRM','871460':'ORCL','552484':'NFLX'};
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const copy=async(value,button)=>{let ok=false;try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(value);ok=true}}catch(_){}if(!ok){try{const ta=document.createElement('textarea');ta.value=value;ta.setAttribute('readonly','');ta.style.position='fixed';ta.style.left='-9999px';document.body.appendChild(ta);ta.select();ta.setSelectionRange(0,ta.value.length);ok=document.execCommand('copy');ta.remove()}catch(_){}}if(button){const old=button.textContent;button.textContent=ok?'✓ kopiert':'Kopieren nicht möglich';setTimeout(()=>button.textContent=old,1300)}};
  function selectedExchange(i){return document.getElementById('exchange'+i)?.value||'AUTO'}
  function applyExchange(input,i){if(!input)return;let v=input.value.trim(),ex=selectedExchange(i),s=suffix[ex];if(!v||ex==='AUTO')return;const upper=v.toUpperCase();let ticker=input.dataset.selected||known[upper]||v;input.dataset.exchange=ex;if(!s)return;const base=String(ticker).replace(/\.(DE|F|VI|L|PA|AS|MI|SW|T|HK|TO)$/i,'');if(/^[A-Za-z][A-Za-z0-9.-]{0,12}$/.test(base))input.value=base+s}
  function wireInputs(){[1,2,3].forEach(i=>{const input=document.getElementById('wkn'+i),sel=document.getElementById('exchange'+i);if(!input||!sel||sel.dataset.compat)return;sel.dataset.compat='1';sel.addEventListener('change',()=>{if(input.dataset.selected||/^[A-Za-z0-9]{6}$/.test(input.value.trim()))applyExchange(input,i)});input.addEventListener('input',()=>{delete input.dataset.selected;delete input.dataset.exchange})})}
  function enhanceCards(){const grid=document.getElementById('top10Grid');if(!grid)return;grid.querySelectorAll('.top10-item').forEach(card=>{const w=card.querySelector('.top10-wkn');if(!w||card.querySelector('.wkn-copy'))return;const value=(w.textContent||'').replace(/^WKN\s*/i,'').trim();if(!/^[A-Z0-9]{6}$/.test(value))return;const b=document.createElement('button');b.type='button';b.className='wkn-copy';b.textContent='WKN kopieren';b.dataset.copy=value;b.style.cssText='margin-top:5px;padding:6px 8px;border:0;border-radius:7px;background:#334155;color:#fff;font-size:10px;font-weight:800;cursor:pointer;width:100%';w.parentElement.appendChild(b)})}
  function wireTop10(){const grid=document.getElementById('top10Grid');if(!grid||grid.dataset.compat)return;grid.dataset.compat='1';grid.addEventListener('click',e=>{const b=e.target.closest('.wkn-copy');if(!b)return;e.preventDefault();e.stopImmediatePropagation();copy(b.dataset.copy,b)},true);new MutationObserver(enhanceCards).observe(grid,{childList:true,subtree:true});enhanceCards()}
  function decorateAnalysis(){const selects=[1,2,3].map(i=>document.getElementById('exchange'+i)?.value).filter(x=>x&&x!=='AUTO');const ex=selects[0];document.querySelectorAll('.stock-group').forEach((group,i)=>{const input=document.getElementById('wkn'+(i+1));const exchange=input?.dataset.exchange||ex;if(!exchange||exchange==='AUTO')return;const summary=group.querySelector('.summary-main');if(summary&&!summary.querySelector('.exchange-badge')){const b=document.createElement('span');b.className='exchange-badge';b.textContent='· '+exchange;b.style.cssText='font-size:10px;color:#0284c7;font-weight:800';summary.appendChild(b)}const title=group.querySelector('.chart-title');if(title&&!title.dataset.exchange){title.dataset.exchange='1';title.textContent+=' · '+exchange}})}
  document.addEventListener('DOMContentLoaded',()=>{wireInputs();wireTop10();const form=document.getElementById('form');if(form)form.addEventListener('submit',()=>{[1,2,3].forEach(i=>applyExchange(document.getElementById('wkn'+i),i))},true);new MutationObserver(()=>{wireInputs();decorateAnalysis()}).observe(document.body,{childList:true,subtree:true});setTimeout(decorateAnalysis,300)});
})();
