(function(){'use strict';
const model=()=>window.AKTScoreModel;
const $=(s,r=document)=>r.querySelector(s);
const monthYear=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleDateString('de-DE',{month:'short',year:'numeric'})};
function formatDates(){document.querySelectorAll('canvas').forEach(c=>{const ch=window.Chart?.getChart(c);if(!ch?.options?.scales?.x)return;const x=ch.options.scales.x;x.ticks=x.ticks||{};x.ticks.callback=function(value){let raw=value;try{raw=this.getLabelForValue(value)}catch(_){}return monthYear(raw)};ch.update('none')});const d=$('.top10-date');if(d?.textContent)d.textContent=d.textContent.replace(/\d{1,2}\.\d{1,2}\.\d{4}/g,monthYear)}
async function scoreTop10(){const m=model();if(!m?.analyse||typeof chartData!=='function')return;const grid=$('.top10-grid');const cards=[...document.querySelectorAll('.top10-item')];await Promise.all(cards.map(async card=>{const symbol=$('.top10-symbol',card)?.textContent?.trim();if(!symbol)return;try{const hit=await chartData(symbol);const z=m.analyse(hit.data||[]);if(!Number.isFinite(z.sc))return;const score=$('.top10-score',card);if(score)score.textContent=z.sc+'/100';const badge=$('.top10-buy',card);if(badge)badge.textContent=m.rec(z.sc);card.dataset.liveScore=String(z.sc)}catch(_){}}));if(grid){cards.sort((a,b)=>(Number(b.dataset.liveScore)||-1)-(Number(a.dataset.liveScore)||-1));cards.forEach((card,i)=>{const rank=$('.top10-rank',card);if(rank)rank.textContent='#'+(i+1);grid.appendChild(card)})}}
function start(){let timer=0;const run=()=>{clearTimeout(timer);timer=setTimeout(()=>{scoreTop10();formatDates()},80)};const root=$('#individuals')||document.body;new MutationObserver(run).observe(root,{childList:true,subtree:true});run();setTimeout(run,1200);setTimeout(run,3500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
