(function(){'use strict';
const VENUES=[['XETRA','Xetra','EUR','€',['DE'] ],['FRANKFURT','Frankfurt','EUR','€',['F'] ],['VIENNA','Wien','EUR','€',['VI'] ],['NYSE','NYSE','USD','$',['NYQ','NYSE'] ],['NASDAQ','NASDAQ','USD','$',['NMS','NGM','NASDAQ'] ],['LONDON','London','GBP','£',['LSE','LON'] ],['PARIS','Paris','EUR','€',['PAR'] ],['AMSTERDAM','Amsterdam','EUR','€',['AMS'] ],['MILAN','Mailand','EUR','€',['MIL'] ],['ZURICH','Zürich','CHF','CHF',['ZRH'] ],['TOKYO','Tokio','JPY','¥',['JPX','TYO'] ],['HONGKONG','Hongkong','HKD','HK$',['HKG'] ],['TORONTO','Toronto','CAD','C$',['TOR'] ]];
const V=Object.fromEntries(VENUES.map(x=>[x[0],x])), suffix={XETRA:'.DE',FRANKFURT:'.F',VIENNA:'.VI',LONDON:'.L',PARIS:'.PA',AMSTERDAM:'.AS',MILAN:'.MI',ZURICH:'.SW',TOKYO:'.T',HONGKONG:'.HK',TORONTO:'.TO'}, cache=new Map(),fxCache=new Map();
const venueInfo=k=>V[k]||V.XETRA;
async function json(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
async function yahooChart(symbol){const key=String(symbol).toUpperCase();if(cache.has(key))return cache.get(key);const end=Math.floor(Date.now()/1000),start=end-60*60*24*1900,url='https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(symbol)+'?period1='+start+'&period2='+end+'&interval=1d&events=history&includeAdjustedClose=true';let z=null;for(const u of [url,'https://corsproxy.io/?url='+encodeURIComponent(url),'https://api.allorigins.win/raw?url='+encodeURIComponent(url)]){try{z=(await json(u)).chart?.result?.[0];if(z)break}catch(_){} }if(!z)throw Error('Keine Kursdaten für '+symbol);const q=z.indicators?.quote?.[0]||{},cl=q.close||[],vol=q.volume||[],data=(z.timestamp||[]).map((t,i)=>({d:new Date(t*1000),c:Number.isFinite(cl[i])?cl[i]:null,v:Number.isFinite(vol[i])?vol[i]:0})).filter(x=>Number.isFinite(x.c));if(data.length<30)throw Error('Zu wenig Historie für '+symbol);const out={data,meta:z.meta||{},symbol};cache.set(key,out);return out}
async function yahooSearch(q){const url='https://query1.finance.yahoo.com/v1/finance/search?q='+encodeURIComponent(q)+'&quotesCount=30&newsCount=0';for(const u of ['https://corsproxy.io/?url='+encodeURIComponent(url),'https://api.allorigins.win/raw?url='+encodeURIComponent(url)]){try{return (await json(u)).quotes||[]}catch(_){}}return []}
async function fx(code){if(code==='EUR')return 1;if(fxCache.has(code))return fxCache.get(code);const pair='EUR'+code+'=X',end=Math.floor(Date.now()/1000),start=end-864000,url='https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(pair)+'?period1='+start+'&period2='+end+'&interval=1d';let z=null;for(const u of [url,'https://corsproxy.io/?url='+encodeURIComponent(url)]){try{z=(await json(u)).chart?.result?.[0];if(z)break}catch(_){}}const c=z?.indicators?.quote?.[0]?.close||[],r=Number(c.filter(Number.isFinite).at(-1));if(!Number.isFinite(r)||r<=0)throw Error('FX '+code);fxCache.set(code,r);return r}
async function convert(data,source,target){source=String(source||'EUR').toUpperCase();target=String(target||'EUR').toUpperCase();if(source===target)return data;const a=await fx(source),b=await fx(target),factor=a/b;return data.map(x=>({...x,c:x.c*factor}))}
function base(s){return String(s||'').replace(/\.(DE|F|VI|L|PA|AS|MI|SW|T|HK|TO|ST|OL|CO|MC|AX|HE|KS|NS)$/i,'')}
function exchangeMatch(q,venue){const info=venueInfo(venue);return info[4].some(e=>String(q.exchange||q.fullExchangeName||q.market||'').toUpperCase().includes(e))}
async function venueSymbol(stock,venue){const b=base(stock.symbol),wanted=venueInfo(venue);if(venue==='XETRA')return b.endsWith('.DE')?b:b+'.DE';const direct=[b+(suffix[venue]||''),String(stock.symbol||'')];for(const s of [...new Set(direct)]){try{await yahooChart(s);return s}catch(_) {}}
const rows=await yahooSearch(stock.symbol||stock.name||b);const hit=rows.find(q=>exchangeMatch(q,venue)&&q.symbol)||rows.find(q=>String(q.symbol||'').toUpperCase()===b.toUpperCase());if(hit){await yahooChart(hit.symbol);return hit.symbol}throw Error('Kein Symbol für '+wanted[1]+' gefunden');}
const fmt=v=>Number(v).toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2});
function card(g,label,value,sub){const c=[...g.querySelectorAll('.card')].find(x=>(x.querySelector('.label')?.textContent||'').trim()===label);if(!c)return;if(value!==undefined){const e=c.querySelector('.value');if(e)e.textContent=value}if(sub!==undefined){const e=c.querySelector('.sub');if(e)e.textContent=sub}}
function redraw(g,data,venue){const canvas=g.querySelector('canvas[id^="price-"]');const ch=canvas&&window.Chart?.getChart(canvas);if(ch){ch.data.labels=data.map(x=>x.d);if(ch.data.datasets?.[0])ch.data.datasets[0].data=data.map(x=>x.c);ch.update('none')}if(canvas)canvas.dataset.venue=venue}
async function refresh(g,venue,sel){if(!g?._stock)return;sel.disabled=true;g.dataset.exchangeLoading='1';try{const symbol=await venueSymbol(g._stock,venue),raw=await yahooChart(symbol),target=venueInfo(venue)[2],source=String(raw.meta?.currency||target).toUpperCase(),data=await convert(raw.data,source,target);g._stock.data=data;g._stock.rawData=raw.data;g._stock.venue=venue;g._stock.dataVenue=venue;g._stock.currency=target;g._stock.symbol=symbol;g.dataset.selectedVenue=venue;redraw(g,data,venue);const z=AKTScoreModel.analyse(data),last=z.last;card(g,'Kurs',fmt(last)+' '+venueInfo(venue)[3],venueInfo(venue)[1]+' · '+target);card(g,'RSI 14',z.rsi.toFixed(1),z.rsi<30?'Überverkauft':z.rsi>70?'Überkauft':'konstruktiv');card(g,'Trend',last>z.sma200?'AUFWÄRTS':'ABWÄRTS','SMA 20/50: '+(last>z.sma20?'positiv':'negativ')+' / '+(last>z.sma50?'positiv':'negativ'));card(g,'Technische Empfehlung',AKTScoreModel.rec(z.score),'Modellscore '+z.score+'/100 · Datenqualität '+z.quality);window.dispatchEvent(new CustomEvent('akt:venue-refreshed',{detail:{group:g,venue,data,currency:target,symbol,score:z.score}}))}catch(e){console.warn('Handelsplatz-Datenwechsel',venue,e);card(g,'Kurs','—',venueInfo(venue)[1]+' · '+venueInfo(venue)[2]+' · keine Kursdaten')}finally{g.dataset.exchangeLoading='';sel.disabled=false}}
function add(g){const c=[...g.querySelectorAll('.card')].find(x=>(x.querySelector('.label')?.textContent||'').trim()==='Kurs');if(!c)return false;let sel=c.querySelector('.venue-select');if(!sel){const w=document.createElement('div');w.className='venue-control';const l=document.createElement('div');l.className='label';l.textContent='Handelsplatz';sel=document.createElement('select');sel.className='venue-select';VENUES.forEach(x=>{const o=document.createElement('option');o.value=x[0];o.textContent=x[1]+' · '+x[2];sel.appendChild(o)});w.append(l,sel);c.appendChild(w);sel.addEventListener('change',()=>refresh(g,sel.value,sel))}sel.value=g.dataset.selectedVenue||'XETRA';sel.hidden=false;sel.style.display='block';sel.style.visibility='visible';if(g.dataset.exchangeInitialized!==sel.value){g.dataset.exchangeInitialized=sel.value;refresh(g,sel.value,sel)}return true}
function install(){document.querySelectorAll('#individuals details.stock-group').forEach(g=>add(g))}
function start(){const root=document.getElementById('individuals');if(root){let t;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(install,80)}).observe(root,{childList:true,subtree:true})}install();[200,600,1200,2500].forEach(x=>setTimeout(install,x))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();})();
