(function(){
'use strict';
const VENUES=[['XETRA','Xetra','.DE'],['FRANKFURT','Frankfurt','.F'],['VIENNA','Wien','.VI'],['NYSE','NYSE',''],['NASDAQ','NASDAQ',''],['LONDON','London','.L'],['PARIS','Paris','.PA'],['AMSTERDAM','Amsterdam','.AS'],['MILAN','Mailand','.MI'],['ZURICH','Zürich','.SW'],['TOKYO','Tokio','.T'],['HONGKONG','Hongkong','.HK'],['TORONTO','Toronto','.TO']];
const suffix=Object.fromEntries(VENUES.map(x=>[x[0],x[2]])),currency={XETRA:'€',FRANKFURT:'€',VIENNA:'€',NYSE:'$',NASDAQ:'$',LONDON:'£',PARIS:'€',AMSTERDAM:'€',MILAN:'€',ZURICH:'CHF',TOKYO:'¥',HONGKONG:'HK$',TORONTO:'C$'},iso={XETRA:'EUR',FRANKFURT:'EUR',VIENNA:'EUR',NYSE:'USD',NASDAQ:'USD',LONDON:'GBP',PARIS:'EUR',AMSTERDAM:'EUR',MILAN:'EUR',ZURICH:'CHF',TOKYO:'JPY',HONGKONG:'HKD',TORONTO:'CAD'},fxCache=new Map(),cache=new Map();
async function json(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
async function chart(symbol){const key=symbol.toUpperCase();if(cache.has(key))return cache.get(key);const end=Math.floor(Date.now()/1000),start=end-60*60*24*1900,url='https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(symbol)+'?period1='+start+'&period2='+end+'&interval=1d&events=history&includeAdjustedClose=true';let z;try{z=(await json(url)).chart?.result?.[0]}catch(_){z=(await json('https://corsproxy.io/?url='+encodeURIComponent(url))).chart?.result?.[0]}if(!z)throw Error('Keine Kursdaten für '+symbol);const q=z.indicators?.quote?.[0]||{},adj=q.close||[],vol=q.volume||[];const data=(z.timestamp||[]).map((t,i)=>({d:new Date(t*1000),c:Number.isFinite(adj[i])?adj[i]:null,v:Number.isFinite(vol[i])?vol[i]:0})).filter(x=>Number.isFinite(x.c));if(data.length<30)throw Error('Zu wenig Historie für '+symbol);const out={data,meta:z.meta||{},symbol};cache.set(key,out);return out}
async function fxRate(code){if(code==='EUR')return 1;if(fxCache.has(code))return fxCache.get(code);const pair='EUR'+code+'=X',end=Math.floor(Date.now()/1000),start=end-60*60*24*10,url='https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(pair)+'?period1='+start+'&period2='+end+'&interval=1d';let z;try{z=(await json(url)).chart?.result?.[0]}catch(_){try{z=(await json('https://corsproxy.io/?url='+encodeURIComponent(url))).chart?.result?.[0]}catch(__){z=null}}const closes=z?.indicators?.quote?.[0]?.close||[];const rate=Number(closes.filter(Number.isFinite).at(-1));if(!Number.isFinite(rate)||rate<=0)throw Error('Wechselkurs EUR/'+code+' konnte nicht geladen werden.');fxCache.set(code,rate);return rate}
async function convertSeries(data,sourceCode,targetCode){if(sourceCode===targetCode)return data;const factor=(await fxRate(targetCode))/(await fxRate(sourceCode));return data.map(x=>({...x,c:x.c*factor}))}
function baseSymbol(s){return String(s.symbol||'').replace(/\.(DE|F|VI|L|PA|AS|MI|SW|T|HK|TO)$/i,'')}
async function loadFor(s,venue){const base=baseSymbol(s),s0=String(s.symbol||'');const isFuture=/=/.test(s0);const candidate=isFuture?s0:base+(suffix[venue]||'');return chart(candidate)}
const fmt=v=>Number(v).toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2});
const money=(v,venue)=>fmt(v)+' '+(currency[venue]||'');
function setCard(group,label,value,sub){const card=[...group.querySelectorAll('.card')].find(c=>(c.querySelector('.label')?.textContent||'').trim()===label);if(!card)return;if(value!==undefined){const v=card.querySelector('.value');if(v)v.textContent=value}if(sub!==undefined){const x=card.querySelector('.sub');if(x)x.textContent=sub}}
function redraw(group,data,days,i,venue){['price','rsi','macd'].forEach(k=>{const c=group.querySelector('#'+k+'-'+i);if(c){const old=Chart.getChart(c);if(old)old.destroy()}});const v=data.slice(-Math.max(30,days||180)),a=v.map(x=>x.c),labels=v.map(x=>x.d.toLocaleDateString('de-DE')),sma=n=>v.map((_,j)=>j<n-1?null:AKTScoreModel.sma(a.slice(0,j+1),n));const pc=group.querySelector('#price-'+i);if(pc)new Chart(pc,{type:'line',data:{labels,datasets:[{label:'Kurs ('+(currency[venue]||'')+')',data:a,pointRadius:0,borderWidth:2},{label:'SMA 20',data:sma(20),pointRadius:0},{label:'SMA 50',data:sma(50),pointRadius:0},{label:'SMA 200',data:sma(200),pointRadius:0}]},options:{responsive:true,maintainAspectRatio:false,animation:false,interaction:{mode:'index',intersect:false}}});const rc=group.querySelector('#rsi-'+i),rs=v.map((_,j)=>j<14?null:AKTScoreModel.rsi(a.slice(0,j+1)));if(rc)new Chart(rc,{type:'line',data:{labels,datasets:[{label:'RSI 14',data:rs,pointRadius:0,borderWidth:2},{label:'70',data:labels.map(()=>70),pointRadius:0},{label:'30',data:labels.map(()=>30),pointRadius:0}]},options:{responsive:true,maintainAspectRatio:false,animation:false,scales:{y:{min:0,max:100}}}});const mc=group.querySelector('#macd-'+i),m=AKTScoreModel.macd(a);if(mc)new Chart(mc,{type:'line',data:{labels,datasets:[{label:'MACD ('+(currency[venue]||'')+')',data:m.values,pointRadius:0,borderWidth:2},{label:'Signal',data:m.signalValues,pointRadius:0}]},options:{responsive:true,maintainAspectRatio:false,animation:false}})}
async function refresh(group,i,venue,sel){sel.disabled=true;try{const raw=await loadFor(group._stock,venue),sourceCode=String(raw.meta?.currency||iso[venue]||'EUR').toUpperCase(),targetCode=iso[venue]||'EUR',data=await convertSeries(raw.data,sourceCode,targetCode);group._stock.data=data;group._stock.rawData=raw.data;group._stock.venue=venue;group._stock.dataVenue=venue;group._stock.symbol=raw.meta?.symbol||baseSymbol(group._stock)+(suffix[venue]||'');const z=AKTScoreModel.analyse(data),rec=AKTScoreModel.rec(z.score),last=z.last,result=group.querySelector('.summary-result');if(result){result.textContent=rec+' · '+z.score+'/100';result.className='summary-result '+(rec==='KAUFEN'?'buy':rec==='NICHT KAUFEN'?'no':'watch')}setCard(group,'Kurs',money(last,venue),'Handelsplatz: '+sel.options[sel.selectedIndex].textContent);setCard(group,'RSI 14',z.rsi.toFixed(1),z.rsi<30?'Überverkauft':z.rsi>70?'Überkauft':'konstruktiv');setCard(group,'Trend',last>z.sma200?'AUFWÄRTS':'ABWÄRTS','SMA 20/50: '+(last>z.sma20?'positiv':'negativ')+' / '+(last>z.sma50?'positiv':'negativ'));setCard(group,'Technische Empfehlung',rec,'Modellscore '+z.score+'/100 · Datenqualität '+z.quality);const meter=group.querySelector('.meter span');if(meter)meter.style.width=z.score+'%';setCard(group,'Momentum 3M',z.momentum3.toFixed(1)+' %');setCard(group,'Momentum 12M',z.momentum12.toFixed(1)+' %');setCard(group,'Volatilität',z.volatility.toFixed(1)+' % p.a.',z.volatility<20?'niedrig':z.volatility<30?'mittel':z.volatility<45?'erhöht':'hoch');setCard(group,'Volumen-Bestätigung',z.volumeRatio.toFixed(2)+'×','20T / 60T');setCard(group,'SMA 20 / 50 / 200',[z.sma20,z.sma50,z.sma200].map(v=>money(v,venue)).join(' / '));setCard(group,'Unterstützung',money(Math.min(...z.close.slice(-60)),venue));setCard(group,'Widerstand',money(Math.max(...z.close.slice(-60)),venue));const why=group.querySelector('.why ul');if(why)why.innerHTML=z.reasons.map(x=>'<li>'+String(x).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))+'</li>').join('');redraw(group,data,window.__aktDays||180,i,venue);window.dispatchEvent(new CustomEvent('akt:venue-refreshed',{detail:{group,venue,data}})}catch(e){console.warn('Handelsplatz nicht verfügbar',venue,e);setCard(group,'Kurs','—','Keine Daten für '+sel.options[sel.selectedIndex].textContent)}finally{sel.disabled=false}}
function addVenue(group,i){const card=[...group.querySelectorAll('.card')].find(c=>(c.querySelector('.label')?.textContent||'').trim()==='Kurs');if(!card||card.querySelector('.venue-select'))return;const wrap=document.createElement('div');wrap.style.cssText='margin-top:8px';const label=document.createElement('div');label.className='label';label.textContent='Handelsplatz';const sel=document.createElement('select');sel.className='venue-select';sel.style.cssText='width:100%;padding:7px;border:1px solid #d1d5db;border-radius:7px;background:#fff;font-weight:700';VENUES.forEach(v=>{const o=document.createElement('option');o.value=v[0];o.textContent=v[1];o.selected=v[0]==='XETRA';sel.appendChild(o)});wrap.append(label,sel);card.appendChild(wrap);sel.addEventListener('change',()=>refresh(group,i,sel.value,sel));setTimeout(()=>refresh(group,i,'XETRA',sel),0)}
function install(){[...document.querySelectorAll('.stock-group')].forEach((g,i)=>{if(g._exchangeInstalled)return;g._exchangeInstalled=true;g._stock={symbol:g.querySelector('.summary-main span')?.textContent.trim()||'',name:g.querySelector('.summary-main b')?.textContent.trim()||'',wkn:(g.textContent.match(/WKN\s+([A-Z0-9]+)/i)||[])[1]||'',data:[]};addVenue(g,i)})}
window.addEventListener('DOMContentLoaded',()=>{const root=document.getElementById('individuals');if(root){let t=0;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(install,120)}).observe(root,{childList:true,subtree:true})}setTimeout(install,300)});
})();