(function(){'use strict';
const VENUES=[['XETRA','Xetra','.DE'],['FRANKFURT','Frankfurt','.F'],['VIENNA','Wien','.VI'],['NYSE','NYSE',''],['NASDAQ','NASDAQ',''],['LONDON','London','.L'],['PARIS','Paris','.PA'],['AMSTERDAM','Amsterdam','.AS'],['MILAN','Mailand','.MI'],['ZURICH','Zürich','.SW'],['TOKYO','Tokio','.T'],['HONGKONG','Hongkong','.HK'],['TORONTO','Toronto','.TO']];
const suffix=Object.fromEntries(VENUES.map(x=>[x[0],x[2]])),iso={XETRA:'EUR',FRANKFURT:'EUR',VIENNA:'EUR',NYSE:'USD',NASDAQ:'USD',LONDON:'GBP',PARIS:'EUR',AMSTERDAM:'EUR',MILAN:'EUR',ZURICH:'CHF',TOKYO:'JPY',HONGKONG:'HKD',TORONTO:'CAD'},currency={XETRA:'€',FRANKFURT:'€',VIENNA:'€',NYSE:'$',NASDAQ:'$',LONDON:'£',PARIS:'€',AMSTERDAM:'€',MILAN:'€',ZURICH:'CHF',TOKYO:'¥',HONGKONG:'HK$',TORONTO:'C$'},fxCache=new Map(),cache=new Map();
async function json(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
async function chart(symbol){const key=symbol.toUpperCase();if(cache.has(key))return cache.get(key);const end=Math.floor(Date.now()/1000),start=end-60*60*24*1900,url='https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(symbol)+'?period1='+start+'&period2='+end+'&interval=1d&events=history&includeAdjustedClose=true';let z;try{z=(await json(url)).chart?.result?.[0]}catch(_){z=(await json('https://corsproxy.io/?url='+encodeURIComponent(url))).chart?.result?.[0]}if(!z)throw Error('Keine Kursdaten für '+symbol);const q=z.indicators?.quote?.[0]||{},cl=q.close||[],vol=q.volume||[],data=(z.timestamp||[]).map((t,i)=>({d:new Date(t*1000),c:Number.isFinite(cl[i])?cl[i]:null,v:Number.isFinite(vol[i])?vol[i]:0})).filter(x=>Number.isFinite(x.c));if(data.length<30)throw Error('Zu wenig Historie für '+symbol);const out={data,meta:z.meta||{},symbol};cache.set(key,out);return out}
async function fxRate(code){if(code==='EUR')return 1;if(fxCache.has(code))return fxCache.get(code);const pair='EUR'+code+'=X',end=Math.floor(Date.now()/1000),start=end-60*60*24*10,url='https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(pair)+'?period1='+start+'&period2='+end+'&interval=1d';let z;try{z=(await json(url)).chart?.result?.[0]}catch(_){try{z=(await json('https://corsproxy.io/?url='+encodeURIComponent(url))).chart?.result?.[0]}catch(__){z=null}}const closes=z?.indicators?.quote?.[0]?.close||[],rate=Number(closes.filter(Number.isFinite).at(-1));if(!Number.isFinite(rate)||rate<=0)throw Error('Wechselkurs EUR/'+code+' konnte nicht geladen werden.');fxCache.set(code,rate);return rate}
async function convertSeries(data,source,target){if(source===target)return data;const sourcePerEur=await fxRate(source),targetPerEur=await fxRate(target),factor=sourcePerEur/targetPerEur;return data.map(x=>({...x,c:x.c*factor}))}
function baseSymbol(s){return String(s.symbol||'').replace(/\.(DE|F|VI|L|PA|AS|MI|SW|T|HK|TO|ST|OL|CO|MC|AX|HE|KS|NS)$/i,'')}
async function loadFor(s,venue){const raw=String(s.symbol||''),isFuture=/=/.test(raw);if(isFuture)return chart(raw);return chart(baseSymbol(s)+(suffix[venue]||''))}
const fmt=v=>Number(v).toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2});
function setCard(g,label,value,sub){const c=[...g.querySelectorAll('.card')].find(x=>(x.querySelector('.label')?.textContent||'').trim()===label);if(!c)return;if(value!==undefined){const v=c.querySelector('.value');if(v)v.textContent=value}if(sub!==undefined){const x=c.querySelector('.sub');if(x)x.textContent=sub}}
function money(v,venue){return fmt(v)+' '+(currency[venue]||'')}
function redraw(g,data,venue){const canvas=g.querySelector('canvas[id^="price-"]');const ch=canvas&&window.Chart?.getChart(canvas);if(!ch)return;ch.data.labels=data.map(x=>x.d);if(ch.data.datasets?.[0])ch.data.datasets[0].data=data.map(x=>x.c);ch.update('none');if(canvas)canvas.dataset.venue=venue}
async function refresh(g,i,venue,sel){if(!g?._stock)return;sel.disabled=true;g.dataset.exchangeLoading='1';try{const raw=await loadFor(g._stock,venue),source=String(raw.meta?.currency||iso[venue]||'EUR').toUpperCase(),target=iso[venue]||'EUR',data=await convertSeries(raw.data,source,target);g._stock.data=data;g._stock.rawData=raw.data;g._stock.venue=venue;g._stock.dataVenue=venue;g._stock.currency=target;g._stock.symbol=raw.meta?.symbol||baseSymbol(g._stock)+(suffix[venue]||'');redraw(g,data,venue);const z=AKTScoreModel.analyse(data),last=z.last;setCard(g,'Kurs',money(last,venue),'Handelsplatz: '+sel.options[sel.selectedIndex].textContent+' · '+target);setCard(g,'RSI 14',z.rsi.toFixed(1),z.rsi<30?'Überverkauft':z.rsi>70?'Überkauft':'konstruktiv');setCard(g,'Trend',last>z.sma200?'AUFWÄRTS':'ABWÄRTS','SMA 20/50: '+(last>z.sma20?'positiv':'negativ')+' / '+(last>z.sma50?'positiv':'negativ'));setCard(g,'Technische Empfehlung',AKTScoreModel.rec(z.score),'Modellscore '+z.score+'/100 · Datenqualität '+z.quality);const meter=g.querySelector('.meter span');if(meter)meter.style.width=z.score+'%';window.dispatchEvent(new CustomEvent('akt:venue-refreshed',{detail:{group:g,venue,data,currency:target,score:z.score}}))}catch(e){console.warn('Handelsplatz nicht verfügbar',venue,e);setCard(g,'Kurs','—','Keine Daten für '+sel.options[sel.selectedIndex].textContent+' · '+(iso[venue]||''))}finally{g.dataset.exchangeLoading='';sel.disabled=false}}
function addVenue(g,i){const c=[...g.querySelectorAll('.card')].find(x=>(x.querySelector('.label')?.textContent||'').trim()==='Kurs');if(!c)return false;let sel=c.querySelector('.venue-select');if(!sel){const wrap=document.createElement('div');wrap.className='venue-control';const l=document.createElement('div');l.className='label';l.textContent='Handelsplatz';sel=document.createElement('select');sel.className='venue-select';VENUES.forEach(v=>{const o=document.createElement('option');o.value=v[0];o.textContent=v[1]+' · '+iso[v[0]];sel.appendChild(o)});wrap.append(l,sel);c.appendChild(wrap);sel.addEventListener('change',()=>{g.dataset.selectedVenue=sel.value;g.dataset.exchangeLoaded='';refresh(g,i,sel.value,sel)})}const wanted=g.dataset.selectedVenue||'XETRA';sel.value=wanted;sel.hidden=false;sel.style.display='block';sel.style.visibility='visible';sel.style.opacity='1';if(g.dataset.exchangeLoaded!==sel.value){g.dataset.exchangeLoaded=sel.value;refresh(g,i,sel.value,sel)}return true}
function install(){document.querySelectorAll('#individuals details.stock-group').forEach((g,i)=>{if(!addVenue(g,i))g.dataset.exchangePending='1'})}
function start(){const root=document.getElementById('individuals');if(root){let t;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(install,100)}).observe(root,{childList:true,subtree:true})}install();[250,750,1500,3000].forEach(ms=>setTimeout(install,ms))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();})();