(function(){
'use strict';
const PERIODS={30:1,90:3,180:6,365:12,1825:60},periodCache=new Map(),$=id=>document.getElementById(id);
async function getJson(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}
function cutoff(months){const d=new Date();d.setHours(0,0,0,0);d.setMonth(d.getMonth()-months);return d}
async function loadPeriod(symbol,months){const key=String(symbol||'').toUpperCase()+'|'+months;if(periodCache.has(key))return periodCache.get(key);const end=Math.floor(Date.now()/1000),start=end-60*60*24*365*8,url='https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(symbol)+'?period1='+start+'&period2='+end+'&interval=1d&events=history&includeAdjustedClose=true';let z;try{z=(await getJson('https://corsproxy.io/?url='+encodeURIComponent(url))).chart?.result?.[0]}catch(_){z=(await getJson(url)).chart?.result?.[0]}if(!z)throw Error('Keine Kursdaten');const q=z.indicators?.quote?.[0]||{},adj=z.indicators?.adjclose?.[0]?.adjclose||[],vol=q.volume||[],all=(z.timestamp||[]).map((t,i)=>({d:new Date(t*1000),c:Number.isFinite(adj[i])?adj[i]:q.close?.[i],v:Number.isFinite(vol[i])?vol[i]:0})).filter(x=>Number.isFinite(x.c));const result={all,data:all.filter(x=>x.d>=cutoff(months))};periodCache.set(key,result);return result}
function updateCharts(i,data){const canvases=[...document.querySelectorAll('.stock-group')][i]?.querySelectorAll('.stock-charts canvas');if(!canvases?.length)return;const a=data.map(x=>x.c),labels=data.map(x=>x.d.toLocaleDateString('de-DE')),sma=n=>a.map((_,j)=>j<n-1?null:AKTScoreModel.sma(a.slice(0,j+1),n)),rsi=a.map((_,j)=>j<14?null:AKTScoreModel.rsi(a.slice(0,j+1))),macd=AKTScoreModel.macd(a);canvases.forEach(canvas=>{const chart=Chart.getChart(canvas);if(!chart)return;chart.data.labels=labels;if(canvas.id.startsWith('price-')){chart.data.datasets[0].data=a;chart.data.datasets[1].data=sma(20);chart.data.datasets[2].data=sma(50);chart.data.datasets[3].data=sma(200)}else if(canvas.id.startsWith('rsi-')){chart.data.datasets[0].data=rsi;chart.data.datasets[1].data=labels.map(()=>70);chart.data.datasets[2].data=labels.map(()=>30)}else if(canvas.id.startsWith('macd-')){const off=Math.max(0,labels.length-macd.values.length);chart.data.datasets[0].data=Array(off).fill(null).concat(macd.values);chart.data.datasets[1].data=Array(off).fill(null).concat(macd.signalValues)}chart.update('none')})}
async function refreshPeriods(days){const months=PERIODS[days]||6;await Promise.all([...document.querySelectorAll('.stock-group')].map(async(group,i)=>{const symbol=group.querySelector('.summary-main span')?.textContent?.trim();if(!symbol)return;try{const p=await loadPeriod(symbol,months);updateCharts(i,p.data)}catch(_){}}))}
function addCacheButton(){if($('clearCacheBtn'))return;const actions=document.querySelector('.search-actions');if(!actions)return;const b=document.createElement('button');b.type='button';b.id='clearCacheBtn';b.className='btn';b.textContent='🧹 Cache leeren';b.style.marginRight='8px';b.style.background='#64748b';b.style.color='#fff';b.onclick=async()=>{b.disabled=true;b.textContent='🧹 wird geleert …';try{try{localStorage.removeItem('aktpro_watchlist_v4')}catch(_){}try{sessionStorage.clear()}catch(_){}try{if(window.caches){const keys=await caches.keys();await Promise.all(keys.map(k=>caches.delete(k)))}}catch(_){} }finally{location.replace(location.pathname+'?cacheReset='+Date.now())}};actions.insertBefore(b,actions.firstChild)}
function addAnalyzeButton(){const actions=document.querySelector('.search-actions');const form=$('form');if(!actions||!form||$('analyzeBtn')){return}const b=document.createElement('button');b.type='submit';b.id='analyzeBtn';b.className='btn';b.textContent='Analysieren';actions.appendChild(b)}
async function copyWkn(wkn,el){let ok=false;try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(wkn);ok=true}}catch(_){}if(!ok){try{const t=document.createElement('textarea');t.value=wkn;t.style.position='fixed';t.style.left='-9999px';document.body.appendChild(t);t.select();ok=document.execCommand('copy');t.remove()}catch(_){} }if(el){const old=el.textContent;el.textContent='WKN '+wkn+' ✓';setTimeout(()=>el.textContent=old,900)}}
function makeWknCopyable(root){root.querySelectorAll('.top10-wkn').forEach(el=>{if(el.dataset.copyReady)return;const m=el.textContent.match(/WKN\s+([A-Z0-9]+)/i);if(!m)return;el.dataset.copyReady='1';el.title='Klicken zum Kopieren';el.style.cursor='pointer';el.onclick=e=>{e.preventDefault();e.stopPropagation();copyWkn(m[1].toUpperCase(),el)}})}
function arrangeMetricCards(root){root.querySelectorAll('.stock-group .stock-body').forEach(body=>{const charts=body.querySelector('.stock-charts'),grid=body.querySelector('.grid');if(!charts||!grid)return;let bottom=body.querySelector('.metrics-below-charts');if(!bottom){bottom=document.createElement('div');bottom.className='metrics-below-charts';bottom.style='display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:9px';charts.insertAdjacentElement('afterend',bottom)}const labels=['Momentum 3M','Momentum 12M','Volatilität','Volumen-Bestätigung','SMA 20 / 50 / 200'];grid.querySelectorAll('.card').forEach(card=>{if(labels.includes(card.querySelector('.label')?.textContent?.trim())&&card.parentElement===grid)bottom.appendChild(card)});if(!bottom.children.length)bottom.remove()})}
const nativeFetch=window.fetch.bind(window);let wknMapPromise=null;async function getWknMap(){if(!wknMapPromise)wknMapPromise=nativeFetch('./wkn-map.json?v=1',{cache:'force-cache'}).then(r=>r.ok?r.json():null).catch(()=>null);return wknMapPromise}
window.fetch=async function(input,init){const url=typeof input==='string'?input:(input&&input.url)||'';if(url==='https://api.openfigi.com/v3/mapping'&&init&&String(init.method||'GET').toUpperCase()==='POST'){try{const body=JSON.parse(init.body||'{}'),id=String(body?.[0]?.idValue||'').trim().toUpperCase(),map=await getWknMap(),item=map?.items?.[id];if(item)return new Response(JSON.stringify([{data:[{ticker:item.ticker,name:item.name,securityDescription:item.name,exchCode:'',marketSector:'Equity',securityType:'Common Stock',securityType2:'Common Stock'}]}]),{status:200,headers:{'Content-Type':'application/json'}})}catch(_){} }return nativeFetch(input,init)};
function loadRuntime(src){const s=document.createElement('script');s.src=src;document.head.appendChild(s)}
loadRuntime('./metal-runtime.js?v=2');loadRuntime('./open-close-runtime.js?v=1');loadRuntime('./ui-runtime.js?v=1');
document.addEventListener('DOMContentLoaded',()=>{addCacheButton();addAnalyzeButton();makeWknCopyable(document);arrangeMetricCards(document);const top10=$('top10Grid'),individuals=$('individuals');if(top10)new MutationObserver(()=>makeWknCopyable(top10)).observe(top10,{childList:true,subtree:true});if(individuals)new MutationObserver(()=>arrangeMetricCards(individuals)).observe(individuals,{childList:true,subtree:true});document.addEventListener('click',e=>{const tab=e.target.closest('.tab');if(tab)setTimeout(()=>refreshPeriods(Number(tab.dataset.d)),150)},{once:false})},{once:true});
})();
