(function(){
  'use strict';

  const PERIODS={30:1,90:3,180:6,365:12,1825:60};
  const periodCache=new Map();
  const $=id=>document.getElementById(id);
  let top10Scores=new Map();

  async function getJson(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return r.json()}

  /* Nur Yahoo-Chart-Requests erhalten einen gezielten Fallback. Andere fetch()-Aufrufe
     der Anwendung bleiben vollständig unverändert. */
  function installChartFallback(){
    if(window.__aktChartFallback)return;
    const originalFetch=window.fetch.bind(window);window.__aktChartFallback=true;
    window.fetch=async function(input,init){
      const url=typeof input==='string'?input:(input?.url||'');
      if(!/query1\.finance\.yahoo\.com\/v8\/finance\/chart\//i.test(url))return originalFetch(input,init);
      try{return await originalFetch(input,init)}catch(primary){
        try{
          const m=url.match(/finance\/chart\/([^?]+)/i);const symbol=decodeURIComponent(m?.[1]||'');if(!symbol)throw primary;
          const stooq=encodeURIComponent(symbol.toLowerCase()+(/\.[a-z]{2,3}$/i.test(symbol)?'':'.us'));
          const d=new Date();const d2=d.toISOString().slice(0,10).replace(/-/g,'');
          const csvUrl='https://stooq.com/q/d/l/?s='+stooq+'&d1=20100101&d2='+d2+'&i=d';
          const proxy='https://corsproxy.io/?url='+encodeURIComponent(csvUrl);
          const r=await originalFetch(proxy,{cache:'no-store'});if(!r.ok)throw primary;
          const text=await r.text(),lines=text.trim().split(/\r?\n/);if(lines.length<3)throw primary;
          const timestamps=[],closes=[],volumes=[];
          lines.slice(1).forEach(line=>{const p=line.split(',');const t=Date.parse(p[1]);const c=Number(p[4]);if(Number.isFinite(t)&&Number.isFinite(c)){timestamps.push(Math.floor(t/1000));closes.push(c);volumes.push(Number(p[6])||0)}});
          if(closes.length<30)throw primary;
          const payload={chart:{result:[{timestamp:timestamps,indicators:{quote:[{close:closes,volume:volumes}],adjclose:[{adjclose:closes}]},meta:{symbol}}],error:null}};
          return new Response(JSON.stringify(payload),{status:200,headers:{'Content-Type':'application/json'}});
        }catch(_){throw primary}
      }
    };
  }

  async function loadTop10Scores(){
    try{const j=await getJson('./top10.json?ts='+Date.now());top10Scores=new Map();(j.items||[]).forEach(x=>{const score=Number(x.score);if(!Number.isFinite(score))return;if(x.wkn)top10Scores.set(String(x.wkn).trim().toUpperCase(),score);if(x.symbol)top10Scores.set(String(x.symbol).trim().toUpperCase(),score)});syncAllScores()}catch(_){top10Scores=new Map()}
  }
  function cutoff(months){const d=new Date();d.setHours(0,0,0,0);d.setMonth(d.getMonth()-months);return d}
  async function loadPeriod(symbol,months){const key=String(symbol||'').toUpperCase()+'|'+months;if(periodCache.has(key))return periodCache.get(key);const end=Math.floor(Date.now()/1000),start=end-60*60*24*365*8,url='https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(symbol)+'?period1='+start+'&period2='+end+'&interval=1d&events=history&includeAdjustedClose=true';let z;try{z=(await getJson(url)).chart?.result?.[0]}catch(_){z=(await getJson('https://corsproxy.io/?url='+encodeURIComponent(url))).chart?.result?.[0]}if(!z)throw Error('Keine Kursdaten');const q=z.indicators?.quote?.[0]||{},adj=z.indicators?.adjclose?.[0]?.adjclose||[],vol=q.volume||[],all=(z.timestamp||[]).map((t,i)=>({d:new Date(t*1000),c:Number.isFinite(adj[i])?adj[i]:q.close?.[i],v:Number.isFinite(vol[i])?vol[i]:0})).filter(x=>Number.isFinite(x.c));const result={all,data:all.filter(x=>x.d>=cutoff(months))};periodCache.set(key,result);return result}
  function getGroupScore(group){const symbol=group.querySelector('.summary-main span')?.textContent?.trim()?.toUpperCase()||'';const m=group.textContent.match(/WKN\s+([A-Z0-9]+)/i);const wkn=m?.[1]?.toUpperCase()||'';if(wkn&&top10Scores.has(wkn))return top10Scores.get(wkn);if(symbol&&top10Scores.has(symbol))return top10Scores.get(symbol);return null}
  function applyTop10Score(group){const score=getGroupScore(group);if(!Number.isFinite(score))return;group.dataset.top10Score=String(score);const rec=score>=90?'KAUFEN':score>=65?'BEOBACHTEN':'NICHT KAUFEN';const result=group.querySelector('.summary-result');if(result){result.textContent=rec+' · '+score+'/100';result.className='summary-result '+(rec==='KAUFEN'?'buy':rec==='NICHT KAUFEN'?'no':'watch')}const card=[...group.querySelectorAll('.card')].find(c=>(c.querySelector('.label')?.textContent||'').trim()==='Technische Empfehlung');if(card){const v=card.querySelector('.score');if(v)v.textContent=rec;const sub=card.querySelector('.sub');if(sub)sub.textContent='Modellscore '+score+'/100';const meter=card.querySelector('.meter span');if(meter)meter.style.width=score+'%'}}
  function syncAllScores(){document.querySelectorAll('.stock-group').forEach(applyTop10Score)}
  function updateCharts(groupIndex,data){const canvases=[...document.querySelectorAll('.stock-group')][groupIndex]?.querySelectorAll('.stock-charts canvas');if(!canvases?.length)return;const a=data.map(x=>x.c),labels=data.map(x=>x.d.toLocaleDateString('de-DE')),sma=n=>a.map((_,i)=>i<n-1?null:AKTScoreModel.sma(a.slice(0,i+1),n)),rsi=a.map((_,i)=>i<14?null:AKTScoreModel.rsi(a.slice(0,i+1))),macd=AKTScoreModel.macd(a);canvases.forEach(canvas=>{const chart=Chart.getChart(canvas);if(!chart)return;chart.data.labels=labels;if(canvas.id.startsWith('price-')){chart.data.datasets[0].data=a;chart.data.datasets[1].data=sma(20);chart.data.datasets[2].data=sma(50);chart.data.datasets[3].data=sma(200)}else if(canvas.id.startsWith('rsi-')){chart.data.datasets[0].data=rsi;chart.data.datasets[1].data=labels.map(()=>70);chart.data.datasets[2].data=labels.map(()=>30)}else if(canvas.id.startsWith('macd-')){const off=Math.max(0,labels.length-macd.values.length);chart.data.datasets[0].data=Array(off).fill(null).concat(macd.values);chart.data.datasets[1].data=Array(off).fill(null).concat(macd.signalValues)}chart.update('none')})}
  async function refreshPeriods(days){const months=PERIODS[days]||6;const groups=[...document.querySelectorAll('.stock-group')];await Promise.all(groups.map(async(group,i)=>{const symbol=group.querySelector('.summary-main span')?.textContent?.trim();if(!symbol)return;try{const p=await loadPeriod(symbol,months);updateCharts(i,p.data)}catch(_){}}))}
  function addCacheButton(){if($('clearCacheBtn'))return;const actions=document.querySelector('.search-actions');if(!actions)return;const b=document.createElement('button');b.type='button';b.id='clearCacheBtn';b.className='btn';b.textContent='🧹 Cache leeren';b.style.marginRight='8px';b.style.background='#64748b';b.style.color='#fff';b.addEventListener('click',async()=>{b.disabled=true;b.textContent='🧹 wird geleert …';try{try{localStorage.clear()}catch(_){ }try{sessionStorage.clear()}catch(_){ }try{document.cookie.split(';').forEach(c=>{const n=c.split('=')[0].trim();if(n)document.cookie=n+'=;expires=Thu, 01 Jan 1970 00:00:00 GMT;path=/'});}catch(_){ }try{if(window.caches){const keys=await caches.keys();await Promise.all(keys.map(k=>caches.delete(k)))}}catch(_){ }}finally{location.replace(location.pathname+'?cacheReset='+Date.now())}});actions.insertBefore(b,actions.firstChild)}
  function openAllDetails(){const groups=[...document.querySelectorAll('.stock-group')];if(groups.length>=2)groups.forEach(g=>g.open=true)}
  async function copyWkn(wkn,el){let ok=false;try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(wkn);ok=true}}catch(_){ }if(!ok){try{const t=document.createElement('textarea');t.value=wkn;t.setAttribute('readonly','');t.style.position='fixed';t.style.left='-9999px';document.body.appendChild(t);t.focus();t.select();ok=document.execCommand('copy');t.remove()}catch(_){ }}const old=el.textContent;el.textContent='WKN '+wkn+' ✓';setTimeout(()=>el.textContent=old,900)}
  function makeWknCopyable(root){root.querySelectorAll('.top10-wkn').forEach(el=>{if(el.dataset.copyReady)return;const m=el.textContent.match(/WKN\s+([A-Z0-9]+)/i);if(!m)return;el.dataset.copyReady='1';el.title='Klicken zum Kopieren';el.style.cursor='pointer';el.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();copyWkn(m[1].toUpperCase(),el)})});root.querySelectorAll('.stock-group .sub').forEach(el=>{if(el.dataset.copyReady)return;const m=el.textContent.match(/WKN\s+([A-Z0-9]+)/i);if(!m)return;const wkn=m[1].toUpperCase(),text=el.textContent,idx=text.toUpperCase().lastIndexOf('WKN '+wkn);if(idx<0)return;el.textContent='';el.append(document.createTextNode(text.slice(0,idx)));const span=document.createElement('span');span.textContent='WKN '+wkn;span.title='Klicken zum Kopieren';span.style.cursor='pointer';span.style.textDecoration='underline';span.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();copyWkn(wkn,span)});el.append(span);el.append(document.createTextNode(text.slice(idx+4+wkn.length)));el.dataset.copyReady='1'})}
  async function resolveWknForSubmit(wkn){const known={'854075':'BRK-A','A0YJQ2':'BRK-B','918422':'NVDA','870747':'MSFT','865985':'AAPL','906866':'AMZN','716460':'SAP','723610':'SIE.DE','840400':'ALV.DE','A11099':'ANET','A1CX3T':'TSLA','A2JG9Z':'AVGO','850628':'JPM','858560':'LLY','938914':'AIR.PA','909800':'TSM','A1J4U4':'ASML','A3CSML':'GE','A0B87V':'CRM','871460':'ORCL','552484':'NFLX'};const k=String(wkn).trim().toUpperCase();if(known[k])return known[k];let data=null;try{const r=await fetch('https://api.openfigi.com/v3/mapping',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify([{idType:'ID_WERTPAPIER',idValue:k}])});if(r.ok)data=await r.json()}catch(_){ }const rows=data?.[0]?.data||[];for(const e of rows){const t=String(e.ticker||'').trim();if(!t)continue;const variants=[t,t+'.DE',t+'.F',t+'.VI',t+'.PA',t+'.AS',t+'.L'];for(const symbol of uniq(variants)){try{const p=await fetch('https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(symbol)+'?period1='+(Math.floor(Date.now()/1000)-60*60*24*370)+'&period2='+Math.floor(Date.now()/1000)+'&interval=1d');if(p.ok&&p.json) {const j=await p.json();if(j.chart?.result?.[0]?.timestamp?.length)return symbol}}catch(_){}}}throw Error('WKN '+k+' konnte keinem handelbaren Aktiensymbol zugeordnet werden.')}
  function installWknSubmitFix(){const form=$('wknForm')||document.querySelector('form');if(!form||form.dataset.wknFix)return;form.dataset.wknFix='1';form.addEventListener('submit',async e=>{if(form.dataset.wknResolved==='1'){form.dataset.wknResolved='';return}const inputs=['wkn1','wkn2','wkn3'].map(id=>$(id)).filter(Boolean);const wknInputs=inputs.filter(i=>/^[A-Z0-9]{6}$/i.test(i.value.trim())&&!i.dataset.selected);if(!wknInputs.length)return;e.preventDefault();e.stopImmediatePropagation();const button=$('analyzeBtn');if(button)button.disabled=true;try{for(const input of wknInputs){const original=input.value.trim().toUpperCase(),symbol=await resolveWknForSubmit(original);input.value=symbol;input.dataset.selected=symbol;input.dataset.resolvedWkn=original}form.dataset.wknResolved='1';form.requestSubmit()}catch(err){const box=$('err');if(box){box.textContent=err.message||'WKN konnte nicht aufgelöst werden.';box.style.display='block'}if(button)button.disabled=false}},true)}
  document.addEventListener('DOMContentLoaded',()=>{installChartFallback();addCacheButton();loadTop10Scores();makeWknCopyable(document);installWknSubmitFix();const target=$('individuals'),top10=$('top10Grid');if(target)new MutationObserver(()=>{openAllDetails();syncAllScores();makeWknCopyable(target)}).observe(target,{childList:true,subtree:true});if(top10)new MutationObserver(()=>makeWknCopyable(top10)).observe(top10,{childList:true,subtree:true});setTimeout(()=>{openAllDetails();syncAllScores();makeWknCopyable(document);installWknSubmitFix()},300);document.addEventListener('click',e=>{const tab=e.target.closest('.tab');if(tab)setTimeout(()=>refreshPeriods(Number(tab.dataset.d)),150);const w=e.target.closest('.top10-wkn');if(w){e.preventDefault();e.stopPropagation();const m=w.textContent.match(/WKN\s+([A-Z0-9]+)/i);if(m)copyWkn(m[1].toUpperCase(),w)}})},{once:true});
})();
