(function(){'use strict';if(window.__AKT_RECOVERY__)return;window.__AKT_RECOVERY__=1;
const VENUES={XETRA:['Xetra','EUR','€','.DE'],FRANKFURT:['Frankfurt','EUR','€','.F'],VIENNA:['Wien','EUR','€','.VI'],NYSE:['NYSE','USD','$',''],NASDAQ:['NASDAQ','USD','$',''],LONDON:['London','GBP','£','.L'],PARIS:['Paris','EUR','€','.PA'],AMSTERDAM:['Amsterdam','EUR','€','.AS'],MILAN:['Mailand','EUR','€','.MI'],ZURICH:['Zürich','CHF','CHF','.SW'],TOKYO:['Tokio','JPY','¥','.T'],HONGKONG:['Hongkong','HKD','HK$','.HK'],TORONTO:['Toronto','CAD','C$','.TO']};
const norm=v=>String(v||'').replace(/^WKN\s*[:#-]?\s*/i,'').replace(/[^A-Za-z0-9]/g,'').toUpperCase();
const enc=v=>btoa(unescape(encodeURIComponent(JSON.stringify(v)))),dec=v=>JSON.parse(decodeURIComponent(escape(atob(v))));const KEY='aktpro_watchlist_v4';
let wl=[];try{wl=JSON.parse(localStorage.getItem(KEY)||'[]')}catch(_){};function cleanList(a){const m=new Map;for(const x of Array.isArray(a)?a:[]){const k=norm(typeof x==='string'?x:x.key||x.wkn);if(k&&!m.has(k))m.set(k,{key:k,title:String(typeof x==='string'?'':x.title||x.name||'').trim()})}return [...m.values()]};wl=cleanList(wl);
function save(){wl=cleanList(wl);try{localStorage.setItem(KEY,JSON.stringify(wl))}catch(_){};try{document.cookie='aktpro_watchlist_sync_v1='+encodeURIComponent(enc(wl))+'; Max-Age=31536000; Path=/; SameSite=Lax'}catch(_){};renderWL();syncStars()}
function renderWL(){let p=document.getElementById('watchlistPanel');if(!p){const top=document.getElementById('top10Panel');if(!top)return;p=document.createElement('section');p.id='watchlistPanel';p.className='watchlist-panel';p.innerHTML='<details open><summary>⭐ Meine Watchlist <span class="watch-count"></span></summary><div class="watchlist-body"><div class="watchlist-items"></div><div class="watch-sync"><button type="button" data-wl-export>Sync-Code</button><input data-wl-code placeholder="Sync-Code einfügen"><button type="button" data-wl-import>Importieren</button></div></div></details>';top.insertAdjacentElement('afterend',p);p.addEventListener('click',function(e){const a=e.target.closest('[data-wl-a]'),r=e.target.closest('[data-wl-r]'),c=e.target.closest('[data-wl-c]');if(a){e.preventDefault();analyse(a.dataset.wlA)}if(r){e.preventDefault();wl=wl.filter(x=>x.key!==norm(r.dataset.wlR));save()}if(c){e.preventDefault();copy(norm(c.dataset.wlC))}if(e.target.closest('[data-wl-export]')){const i=p.querySelector('[data-wl-code');i.value=enc(wl);i.select()}if(e.target.closest('[data-wl-import]')){try{wl=cleanList(dec(p.querySelector('[data-wl-code').value.trim()));save()}catch(_){alert('Ungültiger Sync-Code')}}});}
const b=p.querySelector('.watchlist-items');if(!b)return;b.innerHTML=wl.length?wl.map(x=>'<div class="watch-row"><b>'+String(x.title||x.key).replace(/[<>]/g,'')+'</b><span class="watch-wkn">WKN: '+x.key+'</span><button type="button" data-wl-a="'+x.key+'">Einzelanalyse</button><button type="button" data-wl-c="'+x.key+'">WKN kopieren</button><button type="button" data-wl-r="'+x.key+'">Entfernen</button></div>').join(''):'<div class="watch-empty">Noch keine Titel markiert.</div>';const n=p.querySelector('.watch-count');if(n)n.textContent='('+wl.length+')'}
function copy(v){try{navigator.clipboard.writeText(v);return}catch(_){}const t=document.createElement('textarea');t.value=v;document.body.appendChild(t);t.select();try{document.execCommand('copy')}catch(_){}t.remove()}
function analyse(k){k=norm(k);const g=[...document.querySelectorAll('#individuals .stock-group')].find(x=>norm(x.dataset.wkn||x._stock?.wkn)===k);if(g){g.open=true;g.scrollIntoView({behavior:'smooth',block:'center'});return}const i=document.getElementById('wkn1'),f=document.getElementById('form');if(i&&f){i.value=k;if(f.requestSubmit)f.requestSubmit();else f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}))}}
function starRecord(g){const s=g._stock||{};let key=norm(s.wkn||g.dataset.wkn);if(!key){const txt=g.textContent||'';const m=txt.match(/WKN\s*[:#-]?\s*([A-Z0-9]{6})/i);if(m)key=norm(m[1])}const title=g.querySelector('.summary-main b')?.textContent?.trim()||s.name||'';return key?{key,title}:null}
function syncStars(){document.querySelectorAll('#top10Grid .top10-item,#individuals .stock-group').forEach(g=>{const r=starRecord(g);if(!r)return;g.dataset.watchKey=r.key;let b=g.querySelector('.watch-star');if(!b){b=document.createElement('button');b.type='button';b.className='watch-star';b.textContent='☆';b.title='Zur Watchlist hinzufügen';(g.querySelector('summary')||g).appendChild(b);b.onclick=e=>{e.preventDefault();e.stopPropagation();if(wl.some(x=>x.key===r.key))return;b.textContent='★';wl.push(r);save()}}b.textContent=wl.some(x=>x.key===r.key)?'★':'☆'})}
async function get(url){for(const p of ['https://corsproxy.io/?url=','https://api.allorigins.win/raw?url='])try{const r=await fetch(p+encodeURIComponent(url),{cache:'no-store'});if(r.ok){const j=await r.json();const z=j.chart?.result?.[0]||j;return z}}catch(_){}throw Error('Daten nicht erreichbar')}
const cache=new Map();async function prices(symbol){if(cache.has(symbol))return cache.get(symbol);const e=Math.floor(Date.now()/1000),s=e-86400*1900,z=await get('https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(symbol)+'?period1='+s+'&period2='+e+'&interval=1d&events=history');const q=z.indicators?.quote?.[0]||{},a=z.indicators?.adjclose?.[0]?.adjclose||[],d=(z.timestamp||[]).map((t,i)=>({d:new Date(t*1000),c:Number.isFinite(a[i])?a[i]:q.close?.[i]})).filter(x=>Number.isFinite(x.c));if(d.length<30)throw Error('zu wenig Daten');const out={d,meta:z.meta||{}};cache.set(symbol,out);return out}
function symbol(g,v){let s=g._stock?.symbol||g.querySelector('.summary-main span')?.textContent?.trim()||'';s=s.replace(/\s/g,'');const dot=s.replace(/\.[A-Z]+$/,'');const suf=VENUES[v]?.[3]||'';if(v==='XETRA'&&/\.[A-Z]+$/.test(s))return s;return dot+suf||s}
function findCanvas(g){return g.querySelector('canvas')}
async function exchange(g,v){const info=VENUES[v]||VENUES.XETRA,sel=g.querySelector('.venue-select');if(!sel)return;const token=(g.__venueToken||0)+1;g.__venueToken=token;sel.disabled=true;try{const sy=symbol(g,v),p=await prices(sy);if(g.__venueToken!==token)return;g._stock=g._stock||{};g._stock.data=p.d;g._stock.dataVenue=v;g._stock.currency=info[1];g._stock.symbol=sy;g.dataset.selectedVenue=v;const cv=findCanvas(g),ch=cv&&window.Chart?.getChart(cv);if(ch){ch.data.labels=p.d.map(x=>x.d);if(ch.data.datasets[0])ch.data.datasets[0].data=p.d.map(x=>x.c);ch.update('none')}const last=p.d.at(-1).c;const first=p.d.find(x=>x.d>=Date.now()-180*864e5)||p.d[0];const change=(last/first.c-1)*100;const kurs=[...g.querySelectorAll('.card')].find(c=>c.querySelector('.label')?.textContent?.trim()==='Kurs');if(kurs){const val=kurs.querySelector('.value'),sub=kurs.querySelector('.sub');if(val)val.textContent=last.toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2})+' '+info[2];if(sub)sub.textContent=info[0]+' · '+info[1]}const pc=g.querySelector('.period-change-card .value');if(pc){pc.textContent=(change>=0?'+':'')+change.toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2})+' %';pc.classList.toggle('positive',change>0);pc.classList.toggle('negative',change<0)}g.dispatchEvent(new CustomEvent('akt:venue-refreshed',{bubbles:true,detail:{venue:v,data:p.d,currency:info[1]}}))}catch(e){console.warn('Handelsplatz',e)}finally{if(g.__venueToken===token)sel.disabled=false}}
function addExchange(g){let kurs=[...g.querySelectorAll('.card')].find(c=>c.querySelector('.label')?.textContent?.trim()==='Kurs');if(!kurs)return;let box=kurs.querySelector('.venue-control'),sel=kurs.querySelector('.venue-select');if(!sel){box=document.createElement('div');box.className='venue-control';box.innerHTML='<div class="label">Handelsplatz</div><select class="venue-select"></select>';sel=box.querySelector('select');Object.entries(VENUES).forEach(([k,v])=>{const o=document.createElement('option');o.value=k;o.textContent=v[0]+' · '+v[1];sel.appendChild(o)});kurs.appendChild(box);sel.addEventListener('change',()=>exchange(g,sel.value))}sel.value=g.dataset.selectedVenue||'XETRA';sel.style.display='block';if(!g.dataset.recoveryExchange){g.dataset.recoveryExchange='1';exchange(g,sel.value)}}
function period(g){const a=g._stock?.data||[];if(a.length<2)return;const d=Number(document.querySelector('.tab.active')?.dataset.d||180),end=a.at(-1),first=a.find(x=>x.d>=Date.now()-d*864e5)||a[0],pc=g.querySelector('.period-change-card');if(!pc)return;const x=(end.c/first.c-1)*100,v=pc.querySelector('.value');if(v){v.textContent=(x>=0?'+':'')+x.toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2})+' %';v.classList.toggle('positive',x>0);v.classList.toggle('negative',x<0)}const sub=pc.querySelector('.sub');if(sub)sub.textContent='Datenbasis: '+(g.dataset.selectedVenue||'XETRA')}
function ensurePeriod(g){let row=g.querySelector('.recommendation-row'),grid=g.querySelector('.grid');if(!grid)return;let rec=[...grid.querySelectorAll('.card')].find(c=>c.querySelector('.label')?.textContent?.trim()==='Technische Empfehlung');if(!rec)return;if(!row){row=document.createElement('div');row.className='recommendation-row';grid.appendChild(row)}if(rec.parentElement!==row)row.appendChild(rec);let pc=g.querySelector('.period-change-card');if(!pc){pc=document.createElement('div');pc.className='card period-change-card';pc.innerHTML='<div class="label">Veränderung 6M</div><div class="value neutral">—</div><div class="sub">Datenbasis: XETRA</div>;row.appendChild(pc)}else if(pc.parentElement!==row)row.appendChild(pc);period(g)}
function all(){document.querySelectorAll('#individuals .stock-group').forEach(g=>{ensurePeriod(g);addExchange(g)});syncStars();renderWL()}
function init(){const st=document.createElement('style');st.textContent='.watchlist-panel{display:block!important;visibility:visible!important}.recommendation-row{display:grid!important;grid-template-columns:1fr 1fr!important;gap:8px!important;width:100%!important;align-items:stretch!important}.recommendation-row>.card{min-width:0!important;display:block!important}.period-change-card{display:block!important;visibility:visible!important}.period-change-card .positive{color:#15803d!important}.period-change-card .negative{color:#b91c1c!important}.period-change-card .neutral{color:#64748b!important}.venue-control{display:block!important;visibility:visible!important}.venue-select{display:block!important;visibility:visible!important;width:100%!important;padding:6px!important;background:#fff!important;color:#172033!important;border:1px solid #d1d5db!important;border-radius:8px!important}';document.head.appendChild(st);renderWL();all();const root=document.getElementById('individuals');if(root){let t;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(all,150)}).observe(root,{childList:true,subtree:true})}document.addEventListener('click',e=>{if(e.target.closest('.tab'))setTimeout(all,80)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();})();