(function(){'use strict';
function groups(){const r=document.getElementById('individuals');return r?[...r.querySelectorAll('details.stock-group')]:[]}
function bind(){if(document.documentElement.dataset.ocBound)return;document.documentElement.dataset.ocBound='1';document.addEventListener('click',e=>{const b=e.target.closest&&e.target.closest('#openAll,#closeAll');if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const open=b.id==='openAll';groups().forEach(g=>{g.open=open});requestAnimationFrame(()=>groups().forEach(g=>{g.open=open}))},true)}
function findCard(g,fn){return [...g.querySelectorAll('.card')].find(fn)}
function arrange(g){const cards=[...g.querySelectorAll('.card')];const rec=findCard(g,c=>(c.querySelector('.label')?.textContent||'').trim()==='Technische Empfehlung');const per=findCard(g,c=>c.classList.contains('period-change-card')||c.classList.contains('period-side-card')||/Veränderung/i.test(c.querySelector('.label')?.textContent||''));if(rec&&per){let row=g.querySelector('.recommendation-row');if(!row){row=document.createElement('div');row.className='recommendation-row';rec.parentNode.insertBefore(row,rec)}if(rec.parentElement!==row)row.appendChild(rec);if(per.parentElement!==row)row.appendChild(per)}const course=findCard(g,c=>(c.querySelector('.label')?.textContent||'').trim()==='Kurs');if(course){course.classList.add('venue-visible-card');course.style.height='auto';course.style.maxHeight='none';course.style.overflow='visible'}
const venue=findCard(g,c=>c.querySelector('select.venue-select,select[data-venue],.venue-select'));if(venue)venue.classList.add('venue-visible-card');
// Synchronize the recommendation row heights to the taller card.
const row=g.querySelector('.recommendation-row');if(row){const rs=[...row.children];rs.forEach(c=>{c.style.height='auto'});requestAnimationFrame(()=>{const h=Math.max(...rs.map(c=>c.getBoundingClientRect().height),0);if(h)rs.forEach(c=>c.style.height=h+'px')})}
}
function css(){if(document.getElementById('ui-runtime-style'))return;const s=document.createElement('style');s.id='ui-runtime-style';s.textContent='.recommendation-row{display:grid!important;grid-template-columns:minmax(0,1fr) minmax(0,1fr)!important;gap:8px!important;width:100%!important;grid-column:1 / -1!important;align-items:stretch!important}.recommendation-row>.card{width:auto!important;min-width:0!important;margin:0!important;min-height:92px!important;overflow:hidden!important;padding:9px!important}.recommendation-row .label{font-size:9px!important}.recommendation-row .score,.recommendation-row .value{font-size:16px!important;line-height:1.15!important}.recommendation-row .sub{font-size:9px!important}.recommendation-row .period-change-card .value,.recommendation-row .period-side-card .value{font-size:20px!important}.venue-visible-card{height:auto!important;max-height:none!important;overflow:visible!important}.venue-visible-card .venue-control,.venue-control{display:block!important;visibility:visible!important;opacity:1!important}.venue-select,.venue-visible-card select{display:block!important;visibility:visible!important;opacity:1!important;position:relative!important;z-index:30!important;width:100%!important;min-height:34px!important}@media(max-width:700px){.recommendation-row{grid-template-columns:1fr!important}.recommendation-row>.card{height:auto!important}}';document.head.appendChild(s)}
function init(){bind();css();const root=document.getElementById('individuals');if(!root)return;let t=0;const run=()=>{clearTimeout(t);t=setTimeout(()=>groups().forEach(arrange),60)};new MutationObserver(run).observe(root,{childList:true,subtree:true});run()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();})();
