(function(){'use strict';
const WATCH_KEYS=new Set(['aktpro_watchlist_v4','aktpro_watchlist_v3','aktpro_watchlist_v2']);
function groups(){return Array.from(document.querySelectorAll('#individuals details.stock-group'))}
function bindOpenClose(){if(document.documentElement.dataset.aktOpenCloseBound)return;document.documentElement.dataset.aktOpenCloseBound='1';document.addEventListener('click',function(e){const o=e.target.closest('#openAll'),c=e.target.closest('#closeAll');if(!o&&!c)return;e.preventDefault();e.stopImmediatePropagation();groups().forEach(g=>{g.open=!!o})},true)}
function addCacheButton(){const host=document.querySelector('.search-actions');if(!host||document.getElementById('clearCacheBtn'))return;const b=document.createElement('button');b.type='button';b.id='clearCacheBtn';b.className='btn cache-btn';b.textContent='Cache leeren';b.onclick=clearAnalysisCache;host.insertBefore(b,document.getElementById('analyzeBtn')||null)}
function clearAnalysisCache(){try{for(const k of Object.keys(localStorage)){if(!WATCH_KEYS.has(k))localStorage.removeItem(k)}sessionStorage.clear()}catch(_){}try{if(window.caches)window.caches.keys().then(keys=>Promise.all(keys.map(k=>caches.delete(k)))).catch(()=>{})}catch(_){}try{document.cookie.split(';').forEach(x=>{const n=x.split('=')[0].trim();if(!n||n.startsWith('aktpro_watchlist'))return;document.cookie=n+'=; Max-Age=0; Path=/; SameSite=Lax'})}catch(_){}const u=new URL(location.href);u.searchParams.set('v',Date.now().toString());location.replace(u.href)}
function cardByLabel(g,label){return Array.from(g.querySelectorAll('.card')).find(c=>(c.querySelector('.label')?.textContent||'').trim()===label)}
function recommendationLayout(root){root.querySelectorAll('.stock-group').forEach(g=>{const rec=cardByLabel(g,'Technische Empfehlung');if(!rec)return;rec.classList.add('recommendation-card');rec.querySelectorAll('.tech-recommendation-meter').forEach((m,n)=>{if(n>0)m.remove()});const period=Array.from(g.querySelectorAll('.card')).find(c=>c.classList.contains('period-change-card')||/Veränderung\s*(1M|3M|6M|1J|5J)?/i.test(c.querySelector('.label')?.textContent||''));if(period){period.classList.add('period-side-card');rec.parentElement?.classList.add('recommendation-row');if(rec.nextElementSibling!==period)rec.after(period)}const course=cardByLabel(g,'Kurs');if(course){course.classList.add('course-card','venue-visible-card');course.style.removeProperty('height');course.style.removeProperty('max-height');course.style.removeProperty('overflow');course.querySelectorAll('select').forEach(s=>{s.classList.add('venue-select');s.style.display='block';s.style.visibility='visible';s.style.opacity='1';s.style.width='100%'})}})}
function init(){bindOpenClose();addCacheButton();const root=document.getElementById('individuals');if(root){let timer=0;const run=()=>{clearTimeout(timer);timer=setTimeout(()=>recommendationLayout(root),80)};new MutationObserver(run).observe(root,{childList:true,subtree:true});run()}if(!document.getElementById('ui-runtime-style')){const css=document.createElement('style');css.id='ui-runtime-style';css.textContent='.search-actions{display:flex;justify-content:flex-end;gap:8px;flex-wrap:wrap}.cache-btn{background:#475569!important}.recommendation-row{display:flex!important;gap:8px!important;align-items:stretch!important}.recommendation-card,.period-side-card{width:calc(50% - 4px)!important;display:block!important;vertical-align:top!important;margin:0!important;padding:6px!important;min-height:78px!important;height:78px!important;overflow:hidden!important}.recommendation-card .label,.period-side-card .label{font-size:8px!important}.recommendation-card .value,.recommendation-card .score{font-size:14px!important;line-height:1.05!important;margin-top:1px!important;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.recommendation-card .sub{font-size:8px!important;line-height:1.1!important;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.recommendation-card .meter{height:5px!important;margin-top:3px!important}.period-side-card .value{font-size:18px!important;line-height:1.05!important}.course-card,.venue-visible-card{height:auto!important;min-height:145px!important;max-height:none!important;overflow:visible!important}.course-card select.venue-select{display:block!important;visibility:visible!important;opacity:1!important;height:34px!important;min-height:34px!important;position:relative!important;z-index:5!important}.course-card .label{display:block!important;visibility:visible!important}.course-card .value{font-size:16px!important}@media(max-width:700px){.recommendation-row{display:grid!important;grid-template-columns:1fr!important}.recommendation-card,.period-side-card{width:100%!important;height:78px!important}}';document.head.appendChild(css)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();})();
