(function(){'use strict';
const KEY='aktpro_watchlist_v4',OLD=['aktpro_watchlist_v3','aktpro_watchlist_v2'];
const norm=v=>String(v??'').trim().replace(/^WKN\s*[:#-]?\s*/i,'').replace(/[^A-Za-z0-9]/g,'').toUpperCase();
const clean=v=>String(v??'').trim().replace(/^WKN\s*[:#-]?\s*/i,'');
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const enc=v=>btoa(unescape(encodeURIComponent(JSON.stringify(v)))),dec=v=>JSON.parse(decodeURIComponent(escape(atob(v))));
function sanitize(a){const m=new Map();for(const x of Array.isArray(a)?a:[]){const key=norm(typeof x==='string'?x:x?.key||x?.wkn);if(key&&!m.has(key))m.set(key,{key,title:clean(typeof x==='string'?'':x?.title||x?.name||'')})}return [...m.values()]}
let list=[];try{list=sanitize(JSON.parse(localStorage.getItem(KEY)||'null'))}catch(_){}if(!list.length)for(const k of OLD){try{const a=sanitize(JSON.parse(localStorage.getItem(k)||'[]'));if(a.length){list=a;break}}catch(_){} }
function save(){list=sanitize(list);try{localStorage.setItem(KEY,JSON.stringify(list))}catch(_){}render()}
function add(r){const key=norm(r?.key);if(!key||list.some(x=>x.key===key)){render();return false}list.push({key,title:clean(r.title)});save();return true}
function remove(k){const key=norm(k),before=list.length;list=list.filter(x=>x.key!==key);if(list.length!==before)save();else render()}
function fallback(v){const t=document.createElement('textarea');t.value=v;t.style.cssText='position:fixed;left:-9999px;top:-9999px';document.body.appendChild(t);t.select();try{document.execCommand('copy')}catch(_){}t.remove()}
function copy(v){const key=norm(v);try{if(navigator.clipboard?.writeText){navigator.clipboard.writeText(key).catch(()=>fallback(key));return}}catch(_){}fallback(key)}
function analyse(k){const key=norm(k),g=[...document.querySelectorAll('#individuals .stock-group')].find(x=>norm(x._stock?.wkn||x.dataset.wkn||x.dataset.watchKey)===key);if(g){g.open=true;g.scrollIntoView({behavior:'smooth',block:'center'});return}const i=document.getElementById('wkn1'),f=document.getElementById('form');if(!i||!f)return;i.value=key;delete i.dataset.selected;delete i.dataset.symbol;delete i.dataset.wkn;i.dispatchEvent(new Event('input',{bubbles:true}));if(f.requestSubmit)f.requestSubmit();else f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}))}
function record(el){const s=el?._stock||{},key=norm(s.wkn||el?.dataset.wkn||el?.dataset.watchKey||el?.querySelector('.top10-wkn')?.textContent||''),title=clean(el?.querySelector('.top10-name')?.textContent||el?.querySelector('.summary-main b')?.textContent||s.name||'');return key?{key,title}:null}
function render(){const p=document.getElementById('watchlistPanel');if(!p)return;const body=p.querySelector('.watchlist-items');if(!body)return;body.innerHTML=list.length?list.map(x=>'<div class="watch-row"><b>'+esc(x.title||x.key)+'</b><span class="watch-wkn">WKN: '+esc(x.key)+'</span><button type="button" data-wl-a="'+esc(x.key)+'">Einzelanalyse</button><button type="button" data-wl-c="'+esc(x.key)+'">WKN kopieren</button><button type="button" data-wl-r="'+esc(x.key)+'">Entfernen</button></div>').join(''):'<div class="watch-empty">Noch keine Titel markiert.</div>';const c=p.querySelector('.watch-count');if(c)c.textContent='('+list.length+')'}
function panel(){if(document.getElementById('watchlistPanel'))return;const top=document.getElementById('top10Panel');if(!top)return;const p=document.createElement('section');p.id='watchlistPanel';p.className='watchlist-panel';p.innerHTML='<details open><summary>⭐ Meine Watchlist <span class="watch-count"></span></summary><div class="watchlist-body"><div class="watchlist-items"></div><div class="watch-sync"><button type="button" class="action-btn" data-wl-export>Sync-Code</button><input data-wl-code placeholder="Sync-Code einfügen"><button type="button" class="action-btn" data-wl-import>Importieren</button></div></div></details>';top.insertAdjacentElement('afterend',p);p.addEventListener('click',e=>{const a=e.target.closest('[data-wl-a]');if(a){e.preventDefault();e.stopPropagation();analyse(a.dataset.wlA);return}const c=e.target.closest('[data-wl-c]');if(c){e.preventDefault();e.stopPropagation();copy(c.dataset.wlC);return}const r=e.target.closest('[data-wl-r]');if(r){e.preventDefault();e.stopPropagation();remove(r.dataset.wlR)}});const input=p.querySelector('[data-wl-code]');p.querySelector('[data-wl-export]').onclick=()=>{input.value=enc(list);input.select()};p.querySelector('[data-wl-import]').onclick=()=>{try{list=sanitize(dec(input.value.trim()));save();input.value=''}catch(_){alert('Ungültiger Sync-Code')}};render()}
function stars(){document.querySelectorAll('#top10Grid .top10-item,#individuals .stock-group').forEach(el=>{const r=record(el);if(!r)return;el.dataset.watchKey=r.key;el.dataset.watchTitle=r.title||'';let b=el.querySelector('.watch-star');if(!b){b=document.createElement('button');b.type='button';b.className='watch-star';b.title='Watchlist hinzufügen';b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();if(!list.some(x=>x.key===r.key))b.textContent=add(r)?'★':'★'});(el.querySelector('summary')||el).appendChild(b)}b.textContent=list.some(x=>x.key===r.key)?'★':'☆'})}
function init(){panel();stars();const root=document.getElementById('individuals');if(root){let t;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(stars,150)}).observe(root,{childList:true,subtree:true)}}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();window.AKTWatchlist={add,remove,analyse,copy,get:()=>list.map(x=>({...x}))};})();