(function(){
'use strict';
const KEY='aktpro_watchlist_v4',COOKIE='aktpro_watchlist_sync_v1';
const enc=v=>btoa(unescape(encodeURIComponent(JSON.stringify(v))));
const dec=v=>JSON.parse(decodeURIComponent(escape(atob(v))));
const norm=v=>String(v??'').trim().replace(/^WKN\s*[:#-]?\s*/i,'').trim().toUpperCase();
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function cookieRead(){try{const m=document.cookie.split('; ').find(x=>x.startsWith(COOKIE+'='));return m?dec(decodeURIComponent(m.slice(COOKIE.length+1))):[]}catch(_){return []}}
function cookieWrite(v){try{document.cookie=COOKIE+'='+encodeURIComponent(enc(v))+'; Max-Age=31536000; Path=/; SameSite=Lax'}catch(_) {}}
function cleanTitle(v){return String(v??'').trim().replace(/^WKN\s*[:#-]?\s*/i,'').trim()}
let list=[];
try{const raw=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('aktpro_watchlist_v3')||localStorage.getItem('aktpro_watchlist_v2')||'null');list=Array.isArray(raw)?raw:cookieRead()}catch(_){list=cookieRead()}
if(!list.length)list=cookieRead();
list=list.map(x=>typeof x==='string'?{key:norm(x),title:''}:{key:norm(x.key||x.wkn),title:cleanTitle(x.title||x.name||'')}).filter(x=>x.key);
function save(){const seen=new Set();list=list.filter(x=>{x.key=norm(x.key);x.title=cleanTitle(x.title);if(!x.key||seen.has(x.key))return false;seen.add(x.key);return true});try{localStorage.setItem(KEY,JSON.stringify(list))}catch(_){}cookieWrite(list);render()}
function recordOf(el){if(!el)return null;const stock=el._stock||{};let key=norm(stock.wkn||el.dataset.wkn||el.querySelector('[data-wkn]')?.dataset.wkn||'');if(!key){const text=el.textContent||'';const m=text.match(/\bWKN\s*[:#-]?\s*([A-Z0-9]{4,12})\b/i);if(m)key=norm(m[1])}if(!key)key=norm(el.querySelector('.top10-wkn')?.textContent||'');let title=(el.querySelector('.top10-name')?.textContent||el.querySelector('.summary-main b')?.textContent||stock.name||el.dataset.watchTitle||'').trim();return key?{key,title:title&&norm(title)!==key?cleanTitle(title):''}:null}
function toggle(rec){if(!rec?.key)return;const k=norm(rec.key),i=list.findIndex(x=>x.key===k);if(i>=0)list.splice(i,1);else list.push({key:k,title:cleanTitle(rec.title||'')});save()}
function openDetail(k){k=norm(k);const hit=[...document.querySelectorAll('#individuals .stock-group')].find(g=>norm(g._stock?.wkn||g.dataset.watchKey)===k);if(hit){hit.open=true;hit.scrollIntoView({behavior:'smooth',block:'center'});return}const input=[...document.querySelectorAll('#wkn1,#wkn2,#wkn3')].find(i=>!i.value.trim())||document.getElementById('wkn1');if(!input)return;input.value=k;const form=document.getElementById('form');if(form?.requestSubmit)form.requestSubmit();else form?.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}))}
async function copy(k){k=norm(k);try{await navigator.clipboard.writeText(k)}catch(_){const t=document.createElement('textarea');t.value=k;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove()}}
function render(){const p=document.getElementById('watchlistPanel');if(!p)return;const body=p.querySelector('.watchlist-items');body.innerHTML=list.length?list.map(x=>'<div class="watch-row"><b>'+esc(x.title||x.key)+'</b><span class="watch-wkn">WKN: '+esc(x.key)+'</span><button type="button" data-a="'+esc(x.key)+'">Analyse</button><button type="button" data-c="'+esc(x.key)+'">WKN kopieren</button><button type="button" data-r="'+esc(x.key)+'">Entfernen</button></div>').join(''):'<div class="watch-empty">Noch keine Titel markiert. In Top 10 oder Einzelanalyse auf ☆ klicken.</div>';p.querySelector('.watch-count').textContent='('+list.length+')';p.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>openDetail(b.dataset.a));p.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>copy(b.dataset.c));p.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>toggle({key:b.dataset.r}))}
function addButtons(){document.querySelectorAll('#top10Grid .top10-item,#individuals .stock-group').forEach(el=>{const rec=recordOf(el);if(!rec)return;el.dataset.watchKey=rec.key;el.dataset.watchTitle=rec.title||'';let b=el.querySelector('.watch-star');if(!b){b=document.createElement('button');b.type='button';b.className='watch-star';b.title='Watchlist';const target=el.matches('.stock-group')?(el.querySelector('summary')||el):el;target.style.position='relative';target.appendChild(b)}b.textContent=list.some(x=>x.key===rec.key)?'★':'☆';b.onclick=e=>{e.preventDefault();e.stopPropagation();toggle(rec);b.textContent=list.some(x=>x.key===rec.key)?'★':'☆'}})}
function importList(a){if(!Array.isArray(a))throw Error('invalid');list=a.map(x=>typeof x==='string'?{key:norm(x),title:''}:{key:norm(x.key||x.wkn),title:cleanTitle(x.title||x.name||'')}).filter(x=>x.key);save()}
function makeLink(){const u=new URL(location.href);u.hash='watchlist='+enc(list);return u.href}
function initPanel(){if(document.getElementById('watchlistPanel'))return;const top=document.getElementById('top10Panel');if(!top)return;const p=document.createElement('section');p.id='watchlistPanel';p.className='watchlist-panel';p.innerHTML='<details><summary>⭐ Meine Watchlist <span class="watch-count"></span></summary><div class="watchlist-body"><div class="watchlist-items"></div><div class="watch-sync"><button type="button" class="action-btn" data-wl-link>Link erzeugen</button><button type="button" class="action-btn" data-wl-export>Sync-Code</button><input data-wl-code placeholder="Sync-Code einfügen"><button type="button" class="action-btn" data-wl-import>Importieren</button></div><div class="watch-note">Dauerhaft gespeichert; der Analyse-Cache wird davon getrennt.</div></div></details>';top.insertAdjacentElement('afterend',p);const code=()=>p.querySelector('[data-wl-code]');p.querySelector('[data-wl-link]').onclick=()=>{code().value=makeLink();code().select();copy(code().value)};p.querySelector('[data-wl-export]').onclick=()=>{code().value=enc(list);code().select()};p.querySelector('[data-wl-import]').onclick=()=>{try{const v=code().value.trim();if(v.startsWith('http')){const u=new URL(v),m=u.hash.match(/^#watchlist=(.+)$/);if(!m)throw 0;importList(dec(m[1]))}else importList(dec(v));code().value=''}catch(_){alert('Ungültiger Watchlist-Link oder Sync-Code.')}};render()}
function readHash(){try{const m=location.hash.match(/^#watchlist=(.+)$/);if(m){importList(dec(m[1]));history.replaceState(null,'',location.pathname+location.search)}}catch(_) {}}
const css=document.createElement('style');css.textContent='.watchlist-panel{margin-top:11px;background:#111827;color:#fff;border-radius:15px;overflow:hidden}.watchlist-panel summary{cursor:pointer;padding:14px 17px;font-weight:900;list-style:none}.watchlist-panel summary::-webkit-details-marker{display:none}.watchlist-body{padding:0 11px 11px}.watchlist-items{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px}.watch-row{background:#1f2937;border:1px solid #374151;border-radius:11px;padding:10px;display:flex;flex-wrap:wrap;align-items:center;gap:5px;min-height:80px}.watch-row b{width:100%;font-size:13px}.watch-wkn{width:100%;font-size:9px;color:#94a3b8}.watch-row button{border:0;border-radius:6px;padding:5px 7px;background:#334155;color:#fff;font-size:9px;font-weight:800;cursor:pointer}.watch-empty,.watch-note{font-size:10px;color:#94a3b8}.watch-sync{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.watch-sync input{flex:1;min-width:180px;padding:8px;border:1px solid #475569;border-radius:7px}.watch-star{border:0!important;background:transparent!important;color:#f0b429!important;font-size:20px!important;cursor:pointer!important;line-height:1!important;padding:2px 5px!important;position:absolute!important;right:8px;top:8px;z-index:10}@media(max-width:1100px){.watchlist-items{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:700px){.watchlist-items{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:430px){.watchlist-items{grid-template-columns:1fr}}';document.head.appendChild(css);
function boot(){readHash();initPanel();addButtons();const obs=id=>{const root=document.getElementById(id);if(root){let t;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(addButtons,200)}).observe(root,{childList:true,subtree:true})}};obs('individuals');obs('top10Grid')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();