(function(){'use strict';
const $=id=>document.getElementById(id);
const uniq=a=>[...new Set(a.filter(Boolean))];
const suffixes={US:[''],NYSE:[''],NASDAQ:[''],XETRA:['.DE'],FRANKFURT:['.F','.DE'],LONDON:['.L'],PARIS:['.PA'],AMSTERDAM:['.AS'],MILAN:['.MI'],MADRID:['.MC'],ZURICH:['.SW'],VIENNA:['.VI'],TOKYO:['.T'],HONGKONG:['.HK'],TORONTO:['.TO'],AUSTRALIA:['.AX'],STOCKHOLM:['.ST'],OSLO:['.OL'],COPENHAGEN:['.CO']};
async function jsonGet(url,timeout=9000){const proxies=[u=>'https://corsproxy.io/?url='+encodeURIComponent(u),u=>'https://api.allorigins.win/raw?url='+encodeURIComponent(u)];let last='';for(const make of proxies){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(make(url),{cache:'no-store',signal:c.signal});if(!r.ok)throw Error('HTTP '+r.status);const j=await r.json();clearTimeout(t);return j}catch(e){clearTimeout(t);last=e.name==='AbortError'?'Zeitüberschreitung':e.message}}throw Error(last||'Datenabruf fehlgeschlagen')}
async function yahooChart(symbol){const end=Math.floor(Date.now()/1000),start=end-60*60*24*1900,url='https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(symbol)+'?period1='+start+'&period2='+end+'&interval=1d&events=history&includeAdjustedClose=true';const z=(await jsonGet(url))?.chart?.result?.[0];if(!z)throw Error('keine Kursdaten');const q=z.indicators?.quote?.[0]||{},a=z.indicators?.adjclose?.[0]?.adjclose||[];const data=(z.timestamp||[]).map((t,i)=>({d:new Date(t*1000),c:Number.isFinite(a[i])?a[i]:q.close?.[i]})).filter(x=>Number.isFinite(x.c));if(data.length<200)throw Error('zu wenig Historie');return{data,meta:z.meta||{}}}
async function openFigi(w){const r=await fetch('https://api.openfigi.com/v3/mapping',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify([{idType:'ID_WERTPAPIER',idValue:w}])});if(!r.ok)throw Error('OpenFIGI HTTP '+r.status);return await r.json()}
function equities(rows){return(rows||[]).filter(x=>{const s=((x.marketSector||'')+' '+(x.securityType||'')+' '+(x.securityType2||'')).toLowerCase();return s.includes('equity')||s.includes('common stock')||s.includes('depositary receipt')||s.includes('adr')||s.includes('reit')})}
async function yahooSearch(q){return(await jsonGet('https://query1.finance.yahoo.com/v1/finance/search?q='+encodeURIComponent(q)+'&quotesCount=20&newsCount=0')).quotes||[]}
async function resolveWkn(w){let candidates=[];try{const res=await openFigi(w),rows=equities(res?.[0]?.data);for(const e of rows){const ticker=String(e.ticker||'').trim();if(!ticker)continue;const ex=String(e.exchCode||'').toUpperCase();const ss=suffixes[ex]||['.DE','.F',''];candidates.push(...ss.map(s=>ticker+s));candidates.push(ticker);try{const qs=await yahooSearch(ticker+' '+(e.name||''));candidates.push(...qs.filter(q=>q.quoteType==='EQUITY'&&q.symbol).map(q=>q.symbol))}catch(_){}const hit=await tryCandidates(uniq(candidates),e.name||e.securityDescription||ticker);if(hit)return hit}}catch(_){}
for(const q of [w,'WKN '+w]){try{const qs=await yahooSearch(q),hit=await tryCandidates(qs.filter(x=>x.quoteType==='EQUITY'&&x.symbol).map(x=>x.symbol),qs[0]?.longname||qs[0]?.shortname||w);if(hit)return hit}catch(_){} }throw Error('WKN '+w+' konnte keinem handelbaren Aktiensymbol zugeordnet werden.')}
async function tryCandidates(symbols,name){for(const symbol of uniq(symbols).slice(0,25)){try{const p=await yahooChart(symbol);return{name:name||p.meta?.longName||symbol,symbol,data:p.data,meta:p.meta}}catch(_){}}return null}
async function submit(e){e.preventDefault();const form=$('form');if(!form)return;$('err').style.display='none';$('analyzeBtn').disabled=true;startProgress();try{const vals=[$('wkn1').value.trim().toUpperCase(),$('wkn2').value.trim().toUpperCase(),$('wkn3').value.trim().toUpperCase()].filter(Boolean);const values=uniq(vals);if(!values.length)throw Error('Bitte mindestens eine WKN eingeben.');if(values.length>3)throw Error('Es können maximal drei WKN analysiert werden.');stocks=[];days=180;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.d==='180'));for(let i=0;i<values.length;i++){setProgress(15+i*(60/values.length),'WKN '+values[i]+' wird aufgelöst …',2);stocks.push(await resolveWkn(values[i]));setProgress(35+i*(45/values.length),'Kursdaten für '+values[i]+' geladen …',4)}setProgress(82,'Technische Kennzahlen werden berechnet …',5);$('app').style.display='block';renderIndividuals();finishProgress()}catch(err){$('err').textContent=err.message||'Analyse konnte nicht geladen werden.';$('err').style.display='block';$('progressStatus').textContent='Analyse konnte nicht vollständig abgeschlossen werden.'}finally{$('analyzeBtn').disabled=false}}
function install(){const form=$('form');if(!form)return;form.onsubmit=submit}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
