const KNOWN={'918422':'NVDA','870747':'MSFT','865985':'AAPL','906866':'AMZN','716460':'SAP','723610':'SIE.DE','840400':'ALV.DE','A11099':'ANET','A1CX3T':'TSLA','A2JG9Z':'AVGO','850628':'JPM','858560':'LLY','938914':'AIR.PA','909800':'TSM','A1J4U4':'ASML','A3CSML':'GE','A0B87V':'CRM','871460':'ORCL','552484':'NFLX','A14Y6F':'GOOGL','A1JWVX':'META','863186':'AMD','A2J7M9':'V','A0F602':'MA','871981':'ADBE','878841':'CSCO','883121':'QCOM','852654':'TXN','888351':'COST','856958':'MCD','850663':'KO','852062':'PG','860853':'WMT','853260':'JNJ','A2QA4J':'PLTR','A2PHHG':'UBER','A2JEXP':'BKNG','850598':'CAT','870153':'HON','894648':'LMT','A2DSYC':'LIN','857209':'TMO','888024':'ISRG','851995':'PEP','851399':'IBM','868440':'T','868402':'VZ','852549':'XOM','852552':'CVX','853292':'MC.PA','860180':'SU.PA','886670':'RMS.PA','850727':'TTE.PA','920657':'SAN.PA','863195':'EL.PA','850133':'AI.PA','887771':'BNP.PA','855705':'CS.PA','867475':'DG.PA','555750':'DTE.DE','843002':'MUV2.DE','623100':'IFX.DE','710000':'MBG.DE','519000':'BMW.DE','766403':'VOW3.DE','515100':'BAS.DE','555200':'DHL.DE','703000':'RHM.DE','514000':'DBK.DE','CBK100':'CBK.DE'};
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type'};
const json=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,'Content-Type':'application/json','Cache-Control':'no-store'}});
const norm=v=>String(v??'').trim().replace(/^WKN\s*[:#-]?\s*/i,'').replace(/[^A-Z0-9]/gi,'').toUpperCase();
const avg=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0;
function sma(a,n){return a.length>=n?avg(a.slice(-n)):null}
function ema(a,n){if(a.length<n)return[];const k=2/(n+1);let e=avg(a.slice(0,n)),o=[e];for(let i=n;i<a.length;i++){e=a[i]*k+e*(1-k);o.push(e)}return o}
function rsi(a,n=14){if(a.length<n+1)return 50;let g=0,l=0;for(let i=1;i<=n;i++){const d=a[i]-a[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}g/=n;l/=n;for(let i=n+1;i<a.length;i++){const d=a[i]-a[i-1];g=(g*(n-1)+Math.max(d,0))/n;l=(l*(n-1)+Math.max(-d,0))/n}return l===0?100:100-100/(1+g/l)}
function analyse(rows){const c=rows.map(x=>x.c),last=c.at(-1),s20=sma(c,20),s50=sma(c,50),s200=sma(c,200),rr=rsi(c),e12=ema(c,12),e26=ema(c,26),mac=[];for(let i=0;i<e26.length;i++)mac.push(e12[i+14]-e26[i]);const sig=ema(mac,9),hist=(mac.at(-1)||0)-(sig.at(-1)||0),prevHist=(mac.at(-2)||0)-(sig.at(-2)||0),low1=Math.min(...c.slice(-20,-10)),low2=Math.min(...c.slice(-10)),hi1=Math.max(...c.slice(-20,-10)),hi2=Math.max(...c.slice(-10)),v60=avg(rows.slice(-60).map(x=>x.v)),vr=v60?avg(rows.slice(-20).map(x=>x.v))/v60:1,hi60=Math.max(...c.slice(-60)),dd=(last/hi60-1)*100,mom5=(last/c.at(-6)-1)*100;let score=0;if(s200!=null&&last>s200)score+=12;if(s50!=null&&last>s50)score+=10;if(s20!=null&&last>s20)score+=12;if(rr>=45&&rr<=68)score+=10;else if(rr>=30&&rr<45)score+=6;if(hist>0&&(mac.at(-1)||0)>0)score+=15;else if(hist>0)score+=10;else if(hist>prevHist)score+=5;if(low2>low1*1.01)score+=8;if(hi2>hi1*1.01)score+=8;if(mom5>3)score+=8;else if(mom5>0)score+=4;if(vr>=1.15&&mom5>0)score+=7;else if(vr>=.9)score+=4;if(dd<=-10&&dd>=-35)score+=5;else if(dd>-10)score+=2;score=Math.max(0,Math.min(100,Math.round(score)));let status='ABWÄRTSTREND / KEIN KAUF';if(score>=72)status='BESTÄTIGTER KAUF';else if(score>=58)status='FRÜHES KAUFSIGNAL';else if(score>=42)status='BODENBILDUNG / ABWARTEN';const buyLow=s20?Math.min(last,s20):last,stop=Math.min(...c.slice(-20))*0.98,target=last+(last-stop)*2;return{score,status,last,s20,s50,s200,rsi:rr,momentum5:mom5,volumeRatio:vr,drawdown:dd,buyLow,stop,target,crv:stop<last?(target-last)/(last-stop):null}}
async function prices(symbol){const end=Math.floor(Date.now()/1000),start=end-60*60*24*1900,u='https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(symbol)+'?period1='+start+'&period2='+end+'&interval=1d&events=history&includeAdjustedClose=true';const r=await fetch(u,{headers:{'User-Agent':'AKT-Pro/1.0'}});if(!r.ok)throw Error('Yahoo '+r.status);const j=await r.json(),q=j.chart?.result?.[0],quote=q?.indicators?.quote?.[0]||{},adj=q?.indicators?.adjclose?.[0]?.adjclose||[];return(q?.timestamp||[]).map((t,i)=>({c:Number.isFinite(adj[i])?adj[i]:quote.close?.[i],v:Number(quote.volume?.[i])||0,t})).filter(x=>Number.isFinite(x.c)).slice(-500)}
async function symbolFor(item){if(item.symbol)return String(item.symbol).toUpperCase();const key=norm(item.key);if(KNOWN[key])return KNOWN[key];if(/^[A-Z0-9]{6}$/.test(key))return null;return key}
function fmt(n){return Number.isFinite(n)?n.toFixed(2):'—'}
function signalText(z){return `AKTScore: ${z.score}/100\nSignal: ${z.status}\nKurs: ${fmt(z.last)}\nKaufzone: ${fmt(z.buyLow)}\nStop-Loss: ${fmt(z.stop)}\nKursziel: ${fmt(z.target)}\nCRV: ${fmt(z.crv)}`}
async function sendTelegram(env,chatId,title,body,buttons=[]){const target=String(chatId||env.TELEGRAM_CHAT_ID||'').trim();if(!env.TELEGRAM_BOT_TOKEN||!target)throw Error('Telegram configuration missing');const payload={chat_id:target,text:title+'\n'+body,disable_web_page_preview:true};if(buttons.length)payload.reply_markup={inline_keyboard:buttons};const r=await fetch('https://api.telegram.org/bot'+env.TELEGRAM_BOT_TOKEN+'/sendMessage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw Error('Telegram '+r.status+' '+await r.text());return r.json()}
async function send(env,user,title,body,buttons=[]){return sendTelegram(env,user.telegramChatId||env.TELEGRAM_CHAT_ID,title,body,buttons)}
function menu(){return [[{text:'⭐ Watchlist',callback_data:'watchlist'},{text:'📊 Signale',callback_data:'signale'}],[{text:'🏆 Top 10',callback_data:'top10'},{text:'⚙️ Einstellungen',callback_data:'settings'}],[{text:'ℹ️ Hilfe',callback_data:'help'}]]}
function helpText(){return `AKT-Pro Telegram\n\n/analyse NVDA – Aktie analysieren\n/score NVDA – nur Score\n/add NVDA – Watchlist erweitern\n/remove NVDA – Watchlist verkleinern\n/watchlist – Watchlist anzeigen\n/signale – aktuelle Signale\n/top10 – Top 10 der Watchlist\n/einstellungen – Benachrichtigungen\n/test – Testnachricht\n\nDie Hintergrundprüfung läuft serverseitig.`}
async function telegramApi(env,method,body){const r=await fetch('https://api.telegram.org/bot'+env.TELEGRAM_BOT_TOKEN+'/'+method,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error('Telegram '+method+' '+r.status+' '+await r.text());return r.json()}
function defaultSettings(){return{trend:true,score:true,stop:true,target:true,news:false,morning:true,evening:false}}
async function ensureUser(storage,chatId){const users=await storage.get('users')||{};for(const [token,u] of Object.entries(users))if(String(u.telegramChatId||'')===String(chatId)){u.settings={...defaultSettings(),...(u.settings||{})};return{token,u,users}}const token='telegram:'+String(chatId),u={items:[],telegramChatId:String(chatId),enabled:true,settings:defaultSettings(),updated:Date.now(),lastScan:null};users[token]=u;await storage.put('users',users);return{token,u,users}}
async function saveUser(storage,u){const users=await storage.get('users')||{};for(const [k,v] of Object.entries(users))if(v===u||v.telegramChatId===u.telegramChatId){users[k]=u;break}await storage.put('users',users)}
function settingsButtons(){return [[{text:'Trendwende',callback_data:'set:trend'},{text:'Score',callback_data:'set:score'}],[{text:'Stop-Loss',callback_data:'set:stop'},{text:'Kursziel',callback_data:'set:target'}],[{text:'Morgenbericht',callback_data:'set:morning'},{text:'Abendbericht',callback_data:'set:evening'}],[{text:'🟢 Menü',callback_data:'watchlist'}]]}
function settingsText(u){const s={...defaultSettings(),...(u.settings||{})};return Object.entries({trend:'🔄 Trendwende',score:'📈 AKTScore',stop:'🛑 Stop-Loss',target:'🎯 Kursziel',morning:'🌅 Morgenbericht',evening:'🌙 Abendbericht'}).map(([k,v])=>`${s[k]?'☑️':'☐'} ${v}`).join('\n')}
function watchlistText(u){if(!u.items?.length)return'⭐ Meine Watchlist ist leer.';return u.items.slice(0,100).map((x,i)=>`${i+1}. ${x.title||x.key}${x.symbol?' · '+x.symbol:''}${x.last?.score!=null?' — '+x.last.score+'/100':''}`).join('\n')}
async function analyseItem(item){const symbol=await symbolFor(item);if(!symbol)throw Error('WKN konnte keinem handelbaren Symbol zugeordnet werden.');const rows=await prices(symbol);if(rows.length<60)throw Error('Zu wenige Kursdaten für die Analyse.');return{symbol,z:analyse(rows)}}
async function signalList(u){const out=[];for(const item of (u.items||[]).slice(0,20)){try{const {symbol,z}=await analyseItem(item);out.push(`${z.score>=72?'🟢':z.score>=58?'🟡':'🔴'} ${item.title||item.key} (${symbol}) — ${z.score}/100 — ${z.status}`)}catch{}}return out.length?out.join('\n'):'Keine analysierbaren Titel in der Watchlist.'}
async function top10Text(u){const out=[];for(const item of (u.items||[]).slice(0,50)){try{const {symbol,z}=await analyseItem(item);out.push({name:item.title||item.key,symbol,score:z.score})}catch{}}out.sort((a,b)=>b.score-a.score);return out.slice(0,10).map((x,i)=>`${i+1}. ${x.name} (${x.symbol}) — ${x.score}/100`).join('\n')||'Keine analysierbaren Titel.'}
async function answerCallback(env,storage,q){await telegramApi(env,'answerCallbackQuery',{callback_query_id:q.id});const {u}=await ensureUser(storage,q.message.chat.id),a=q.data;if(a==='watchlist')await send(env,u,'⭐ Meine Watchlist',watchlistText(u),menu());else if(a==='signale')await send(env,u,'📊 AKT-Pro Signale',await signalList(u),menu());else if(a==='top10')await send(env,u,'🏆 AKT-Pro TOP 10',await top10Text(u),menu());else if(a==='settings')await send(env,u,'⚙️ Benachrichtigungen',settingsText(u),settingsButtons());else if(a.startsWith('set:')){const k=a.slice(4);u.settings[k]=!u.settings[k];await saveUser(storage,u);await send(env,u,'⚙️ Benachrichtigungen',settingsText(u),settingsButtons())}else if(a.startsWith('add:')){const symbol=a.slice(4);if(!u.items)u.items=[];if(!u.items.some(i=>String(i.symbol||i.key).toUpperCase()===symbol)){u.items.push({key:symbol,symbol,title:symbol});await saveUser(storage,u)}await send(env,u,'⭐ Watchlist',symbol+' wurde hinzugefügt.',menu());else if(a==='help')await send(env,u,'ℹ️ Hilfe',helpText(),menu())}
async function handleCommand(env,storage,chatId,text){const {u}=await ensureUser(storage,chatId);const [raw,...args]=String(text||'').trim().split(/\s+/),cmd=raw.toLowerCase().split('@')[0],arg=args.join(' ').trim();try{
if(cmd==='/start'||cmd==='/help'){await send(env,u,'🤖 AKT-Pro Telegram',helpText(),menu());return}
if(cmd==='/watchlist'){await send(env,u,'⭐ Meine Watchlist',watchlistText(u),menu());return}
if(cmd==='/signale'){await send(env,u,'📊 AKT-Pro Signale',await signalList(u),menu());return}
if(cmd==='/top10'){await send(env,u,'🏆 AKT-Pro TOP 10',await top10Text(u),menu());return}
if(cmd==='/einstellungen'){await send(env,u,'⚙️ Benachrichtigungen',settingsText(u),settingsButtons());return}
if(cmd==='/test'){await send(env,u,'🔔 AKT-Pro · Telegram-Test','Die Telegram-Hintergrundbenachrichtigung funktioniert.');return}
if(cmd==='/add'){if(!arg)return send(env,u,'⭐ Watchlist','Verwendung: /add NVDA');const key=norm(arg),symbol=KNOWN[key]||(/^[A-Z]{1,6}([.][A-Z]{1,3})?$/.test(key)?key:null);if(!symbol)return send(env,u,'⚠️ Watchlist','Symbol/WKN nicht erkannt. Beispiel: /add NVDA');if(!u.items)u.items=[];if(u.items.some(i=>String(i.symbol||i.key).toUpperCase()===symbol))return send(env,u,'⭐ Watchlist',symbol+' ist bereits in deiner Watchlist.');u.items.push({key:symbol,symbol,title:symbol});await saveUser(storage,u);await send(env,u,'⭐ Watchlist',symbol+' wurde hinzugefügt.');return}
if(cmd==='/remove'){if(!arg)return send(env,u,'⭐ Watchlist','Verwendung: /remove NVDA');const key=norm(arg),symbol=KNOWN[key]||key;const before=u.items?.length||0;u.items=(u.items||[]).filter(i=>String(i.symbol||i.key).toUpperCase()!==symbol);await saveUser(storage,u);await send(env,u,'⭐ Watchlist',before===u.items.length?symbol+' war nicht in der Watchlist.':symbol+' wurde entfernt.');return}
if(cmd==='/score'||cmd==='/analyse'){if(!arg)return send(env,u,'📊 Analyse','Verwendung: /analyse NVDA');const item={key:norm(arg),symbol:KNOWN[norm(arg)]||undefined,title:arg.toUpperCase()};const {symbol,z}=await analyseItem(item);await send(env,u,'📊 '+symbol,signalText(z),[[{text:'⭐ Zur Watchlist',callback_data:'add:'+symbol}]]);return}
await send(env,u,'❓ Unbekannter Befehl','/help zeigt alle verfügbaren Befehle.',menu())
}catch(e){await send(env,u,'⚠️ AKT-Pro Fehler',String(e.message||e))}}
async function processUpdates(env,storage){if(!env.TELEGRAM_BOT_TOKEN)return;const meta=await storage.get('telegram')||{};let offset=Number(meta.offset||0),page=0;while(page++<5){const data=await telegramApi(env,'getUpdates',{offset,limit:100,timeout:0,allowed_updates:['message','callback_query']});const updates=data.result||[];if(!updates.length)break;for(const x of updates){offset=Math.max(offset,Number(x.update_id)+1);if(x.callback_query)await answerCallback(env,storage,x.callback_query);else if(x.message?.chat?.id&&x.message.text)await handleCommand(env,storage,x.message.chat.id,x.message.text)}await storage.put('telegram',{offset})}}
async function dailyReports(env,storage){const users=await storage.get('users')||{};const now=new Date(),hour=now.getUTCHours(),minute=now.getUTCMinutes();if(minute!==0)return;for(const u of Object.values(users)){if(!u.enabled||!u.items?.length)continue;if(u.settings?.morning&&hour===6)await send(env,u,'🌅 AKT-Pro MORGENCHECK',await signalList(u),menu());if(u.settings?.evening&&hour===19)await send(env,u,'🌙 AKT-Pro ABENDCHECK',await signalList(u),menu())}}
async function scanUsers(env,storage){const users=await storage.get('users')||{};for(const u of Object.values(users)){if(!u.enabled||!u.items?.length)continue;for(const item of u.items){try{const {symbol,z}=await analyseItem(item),old=item.last;item.last={score:z.score,status:z.status,symbol,at:Date.now(),stop:z.stop,target:z.target,last:z.last};const band=s=>s>=72?'buy':s>=58?'early':'low';const events=[];if(old){if(old.status!==z.status&&u.settings?.trend!==false)events.push(['🔄 Trendwende',old.status+' → '+z.status]);if(band(old.score)!==band(z.score)&&u.settings?.score!==false)events.push(['📈 AKTScore',old.score+' → '+z.score]);if(u.settings?.stop!==false&&old.last&&z.last<=z.stop&&old.last>z.stop)events.push(['🛑 Stop-Loss','Kurs '+fmt(z.last)+' unter '+fmt(z.stop)]);if(u.settings?.target!==false&&old.last&&z.last>=z.target&&old.last<z.target)events.push(['🎯 Kursziel','Kurs '+fmt(z.last)+' hat '+fmt(z.target)+' erreicht'])}for(const [title,body] of events)await send(env,u,(item.title||symbol)+' · '+title,body+'\n\n'+signalText(z))}catch(e){item.lastError=String(e)}}u.lastScan=Date.now()}await storage.put('users',users)}
export class WatchlistAlarm{constructor(state,env){this.state=state;this.env=env}
async fetch(req){const u=new URL(req.url);if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});
if(req.method==='POST'&&u.pathname==='/sync'){const x=await req.json();if(!x.token)return new Response('token required',{status:400,headers:cors});const users=await this.state.storage.get('users')||{},old=users[x.token]||{};const incoming=Array.isArray(x.items)?x.items.slice(0,1000):[];const oldByKey=new Map((old.items||[]).map(i=>[norm(i.key),i]));users[x.token]={items:incoming.map(i=>({...i,last:oldByKey.get(norm(i.key))?.last})),topic:String(x.topic||old.topic||''),telegramChatId:String(x.telegramChatId||old.telegramChatId||''),enabled:!!x.enabled,settings:{...defaultSettings(),...(old.settings||{})},updated:Date.now(),lastScan:old.lastScan||null};await this.state.storage.put('users',users);await this.state.storage.setAlarm(Date.now()+60*60*1000);return json({ok:true,nextScan:Date.now()+60*60*1000,telegram:!!(this.env.TELEGRAM_BOT_TOKEN&&(users[x.token].telegramChatId||this.env.TELEGRAM_CHAT_ID))})}
if(req.method==='POST'&&u.pathname==='/test'){const x=await req.json(),users=await this.state.storage.get('users')||{},v=users[x.token];if(!v)return new Response('watchlist not synchronized',{status:400,headers:cors});try{await sendTelegram(this.env,v.telegramChatId||this.env.TELEGRAM_CHAT_ID,'AKT-Pro · Telegram-Test','Die Telegram-Hintergrundbenachrichtigung funktioniert.');return json({ok:true,channel:'telegram'})}catch(e){return json({ok:false,channel:'telegram',error:String(e)},502)}}
if(req.method==='POST'&&u.pathname==='/cron'){await processUpdates(this.env,this.state.storage);await dailyReports(this.env,this.state.storage);await scanUsers(this.env,this.state.storage);return json({ok:true})}
if(req.method==='GET'&&u.pathname==='/status'){const token=u.searchParams.get('token'),users=await this.state.storage.get('users')||{},v=users[token];return json({enabled:!!v?.enabled,items:v?.items?.length||0,lastScan:v?.lastScan||null,channel:this.env.TELEGRAM_BOT_TOKEN&&(v?.telegramChatId||this.env.TELEGRAM_CHAT_ID)?'telegram':'none'})}
return new Response('not found',{status:404,headers:cors})}
async alarm(){await scanUsers(this.env,this.state.storage);await this.state.storage.setAlarm(Date.now()+60*60*1000)}}
export default{async fetch(req,env){if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(new URL(req.url).pathname==='/telegram/health')return json({ok:true,telegram:!!env.TELEGRAM_BOT_TOKEN});const id=env.WATCHLIST.idFromName('global');return env.WATCHLIST.get(id).fetch(req)},async scheduled(controller,env,ctx){const id=env.WATCHLIST.idFromName('global');const stub=env.WATCHLIST.get(id);ctx.waitUntil(stub.fetch(new Request('https://internal/cron',{method:'POST'})))}}