const PREFIX='aktpro-trend-';
const KNOWN={'918422':'NVDA','870747':'MSFT','865985':'AAPL','906866':'AMZN','716460':'SAP','723610':'SIE.DE','840400':'ALV.DE','A11099':'ANET','A1CX3T':'TSLA','A2JG9Z':'AVGO','850628':'JPM','858560':'LLY','938914':'AIR.PA','909800':'TSM','A1J4U4':'ASML','A3CSML':'GE','A0B87V':'CRM','871460':'ORCL','552484':'NFLX','A14Y6F':'GOOGL','A1JWVX':'META','863186':'AMD','A2J7M9':'V','A0F602':'MA','871981':'ADBE','878841':'CSCO','883121':'QCOM','852654':'TXN','888351':'COST','856958':'MCD','850663':'KO','852062':'PG','860853':'WMT','853260':'JNJ','A2QA4J':'PLTR','A2PHHG':'UBER','A2JEXP':'BKNG','850598':'CAT','870153':'HON','894648':'LMT','A2DSYC':'LIN','857209':'TMO','888024':'ISRG','851995':'PEP','851399':'IBM','868440':'T','868402':'VZ','852549':'XOM','852552':'CVX','853292':'MC.PA','860180':'SU.PA','886670':'RMS.PA','850727':'TTE.PA','920657':'SAN.PA','863195':'EL.PA','850133':'AI.PA','887771':'BNP.PA','855705':'CS.PA','867475':'DG.PA','555750':'DTE.DE','843002':'MUV2.DE','623100':'IFX.DE','710000':'MBG.DE','519000':'BMW.DE','766403':'VOW3.DE','515100':'BAS.DE','555200':'DHL.DE','703000':'RHM.DE','514000':'DBK.DE','CBK100':'CBK.DE'};
const norm=v=>String(v??'').trim().replace(/^WKN\s*[:#-]?\s*/i,'').replace(/[^A-Z0-9]/gi,'').toUpperCase();
const avg=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0;
function sma(a,n){return a.length>=n?avg(a.slice(-n)):null}
function ema(a,n){if(a.length<n)return[];const k=2/(n+1);let e=avg(a.slice(0,n)),o=[e];for(let i=n;i<a.length;i++){e=a[i]*k+e*(1-k);o.push(e)}return o}
function rsi(a,n=14){if(a.length<n+1)return 50;let g=0,l=0;for(let i=1;i<=n;i++){const d=a[i]-a[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}g/=n;l/=n;for(let i=n+1;i<a.length;i++){const d=a[i]-a[i-1];g=(g*(n-1)+Math.max(d,0))/n;l=(l*(n-1)+Math.max(-d,0))/n}return l===0?100:100-100/(1+g/l)}
function analyse(rows){const c=rows.map(x=>x.c),last=c.at(-1),s20=sma(c,20),s50=sma(c,50),s200=sma(c,200),rr=rsi(c),e12=ema(c,12),e26=ema(c,26),mac=[];for(let i=0;i<e26.length;i++)mac.push(e12[i+14]-e26[i]);const sig=ema(mac,9),hist=(mac.at(-1)||0)-(sig.at(-1)||0),prevHist=(mac.at(-2)||0)-(sig.at(-2)||0),low1=Math.min(...c.slice(-20,-10)),low2=Math.min(...c.slice(-10)),hi1=Math.max(...c.slice(-20,-10)),hi2=Math.max(...c.slice(-10)),vr=avg(rows.slice(-60).map(x=>x.v))?avg(rows.slice(-20).map(x=>x.v))/avg(rows.slice(-60).map(x=>x.v)):1,hi60=Math.max(...c.slice(-60)),dd=(last/hi60-1)*100,mom5=(last/c.at(-6)-1)*100;let score=0;if(s200!=null&&last>s200)score+=12;if(s50!=null&&last>s50)score+=10;if(s20!=null&&last>s20)score+=12;if(rr>=45&&rr<=68)score+=10;else if(rr>=30&&rr<45)score+=6;if(hist>0&&(mac.at(-1)||0)>0)score+=15;else if(hist>0)score+=10;else if(hist>prevHist)score+=5;if(low2>low1*1.01)score+=8;if(hi2>hi1*1.01)score+=8;if(mom5>3)score+=8;else if(mom5>0)score+=4;if(vr>=1.15&&mom5>0)score+=7;else if(vr>=.9)score+=4;if(dd<=-10&&dd>=-35)score+=5;else if(dd>-10)score+=2;score=Math.max(0,Math.min(100,Math.round(score)));let status='ABWARTEN';if(score>=72)status='BESTÄTIGTER KAUF';else if(score>=58)status='FRÜHES KAUFSIGNAL';else if(score>=42)status='BODENBILDUNG / ABWARTEN';else status='ABWÄRTSTREND / KEIN KAUF';return{score,status}}
async function prices(symbol){const end=Math.floor(Date.now()/1000),start=end-60*60*24*1900,u='https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(symbol)+'?period1='+start+'&period2='+end+'&interval=1d&events=history&includeAdjustedClose=true';const r=await fetch(u,{headers:{'User-Agent':'AKT-Pro/1.0'},cf:{cacheTtl:300}});if(!r.ok)throw Error('Yahoo '+r.status);const j=await r.json(),q=j.chart?.result?.[0],quote=q?.indicators?.quote?.[0]||{},adj=q?.indicators?.adjclose?.[0]?.adjclose||[];return(q?.timestamp||[]).map((t,i)=>({c:Number.isFinite(adj[i])?adj[i]:quote.close?.[i],v:Number(quote.volume?.[i])||0})).filter(x=>Number.isFinite(x.c)).slice(-500)}
async function symbolFor(item){if(item.symbol)return item.symbol;if(KNOWN[item.key])return KNOWN[item.key];return /^[A-Z0-9]{6}$/.test(item.key)?null:item.key}
async function send(topic,title,body){if(!topic)return;const r=await fetch('https://ntfy.sh/'+encodeURIComponent(topic),{method:'POST',headers:{Title:title,Priority:'high',Tags:'chart_with_upwards_trend'},body});if(!r.ok)throw Error('ntfy '+r.status)}
export class WatchlistAlarm{constructor(state,env){this.state=state;this.env=env}
 async fetch(req){const u=new URL(req.url);if(req.method==='POST'&&u.pathname==='/sync'){const x=await req.json();if(!x.token)return new Response('token required',{status:400});const users=await this.state.storage.get('users')||{};users[x.token]={items:Array.isArray(x.items)?x.items.slice(0,1000):[],topic:String(x.topic||''),enabled:!!x.enabled,updated:Date.now()};await this.state.storage.put('users',users);await this.state.storage.setAlarm(Date.now()+60*60*1000);return Response.json({ok:true,nextScan:Date.now()+60*60*1000})}if(req.method==='POST'&&u.pathname==='/test'){const x=await req.json();if(!x.token)return new Response('token required',{status:400});const users=await this.state.storage.get('users')||{},v=users[x.token];if(!v?.topic)return new Response('ntfy topic missing',{status:400});await send(v.topic,'AKT-Pro · Test','Watchlist-Hintergrundbenachrichtigung funktioniert.');return Response.json({ok:true})}if(req.method==='GET'&&u.pathname==='/status'){const token=u.searchParams.get('token'),users=await this.state.storage.get('users')||{},v=users[token];return Response.json({enabled:!!v?.enabled,items:v?.items?.length||0,lastScan:v?.lastScan||null})}return new Response('not found',{status:404})}
 async alarm(){const users=await this.state.storage.get('users')||{};for(const [token,u] of Object.entries(users)){if(!u.enabled||!u.items?.length)continue;for(const item of u.items){try{const symbol=await symbolFor(item);if(!symbol)continue;const rows=await prices(symbol);if(rows.length<60)continue;const z=analyse(rows),old=u.items.find(x=>norm(x.key)===norm(item.key))?.last;item.last={score:z.score,status:z.status,symbol,at:Date.now()};if(old&&(old.status!==z.status||((old.score<58)!=(z.score<58))||((old.score<72)!=(z.score<72))))await send(u.topic,'📈 '+(item.title||item.key)+' · Trendwende',old.status+' → '+z.status+' · Score '+old.score+' → '+z.score)}catch(e){item.lastError=String(e)}}u.lastScan=Date.now()}await this.state.storage.put('users',users);await this.state.storage.setAlarm(Date.now()+60*60*1000)} }
export default{async fetch(req,env){const id=env.WATCHLIST.idFromName('global');return env.WATCHLIST.get(id).fetch(new Request(new URL(req.url).pathname+new URL(req.url).search,req))}}
